### ISSUE TITLE
support for PEP 396 Module Version

### ISSUE THREAD

**Issue by deepcoder** [crsmithdev/arrow#131]
when I try:

arrow.__version__

results in:

Traceback (most recent call last):

  File "<ipython-input-11-bfb7e065acb3>", line 1, in <module>
    arrow.__version__

AttributeError: 'module' object has no attribute '__version__'

----
pkg_resources yields a result, but the guidance in PEP 396 seems a good path.

pkg_resources.get_distribution("arrow").version

'0.4.2'

Thx for review! Great package!!!! Super work!

**Comment by andrewelkins** [comment]
I believe this is fixed. Please reopen if it isn't.
