### ISSUE TITLE
Incorrect parse of ISO-8601 string

### ISSUE THREAD

**Issue by csu** [crsmithdev/arrow#143]
When I try to use:

    test = arrow.get('2013-08-04T12:49:18.518+01:00')
    print test.datetime

I get:

    2013-08-04 12:49:18.000518+01:00

Arrow seems to append an additional three 0's to the milliseconds?

**Comment by EverpathDano** [comment]
Look like commit da7725eb99b19225a1bb82b60311483a5c5e238c has fixed this, and is live as of Arrow v0.5.0?

**Comment by andrewelkins** [comment]
Yep this is fixed as of 0.5.0
