### ISSUE TITLE
Creating new Arrows with a timezone string is slow

### ISSUE THREAD

**Issue by jkleint** [crsmithdev/arrow#148]
~66X slower than re-using an existing `tzinfo` object:

```
In [1]: from datetime import datetime

In [2]: import arrow

In [3]: d = datetime.now()

In [4]: %timeit arrow.get(d, 'US/Eastern')
10000 loops, best of 3: 138 µs per loop

In [5]: tz = arrow.get(d, 'US/Eastern').tzinfo

In [6]: %timeit arrow.get(d, tz)
100000 loops, best of 3: 2.08 µs per loop
```

It looks like `dateutil.tz.tzfile` is actually reading and parsing the zone info files every time you create one.  

Since presumably `tzinfo` objects are immutable, (hopefully) the zone info files don't change while your program is running, and there are only a limited number of zones (less than 1800 on Ubuntu), maybe it makes sense to cache timezones, or even make them singletons?

**Comment by JamshedVesuna** [comment]
+1 would be great to see a fix for this

**Comment by systemcatch** [comment]
Can someone double check this? I think the problem has been fixed.
```shell
In [8]: %timeit arrow.get(d, tz)
The slowest run took 5.12 times longer than the fastest. This could mean that an int
ermediate result is being cached.
100000 loops, best of 5: 4.8 µs per loop
In [9]: %timeit arrow.get(d, 'US/Eastern')
The slowest run took 4.09 times longer than the fastest. This could mean that an int
ermediate result is being cached.
100000 loops, best of 5: 9.5 µs per loop
```

**Comment by systemcatch** [comment]
Closing for now, let me know if there's still a problem.
