### ISSUE TITLE
Parsing foreign (i.e ARABIC-INDIC) timestamps with arrow does not work

### ISSUE THREAD

**Issue by brainstorm** [crsmithdev/arrow#152]
While collecting information from an iOS app, the following datestamps appeared (ignore line-numbers on first column):

```
3351    ۱۳۹۳-۰۲-۱۰
3352    ۱۳۹۳-۰۲-۱۰
3353    २०१४-०४-२८
3354    २०१४-०४-२८
```

Which can be understood in hexa:

```
$ echo "٢٠١٤-٠٥-٠١" | hexdump
0000000 d9 a2 d9 a0 d9 a1 d9 a4 2d d9 a0 d9 a5 2d d9 a0
0000010 d9 a1 0a
0000013

... timestamp above being: 2014-05-01
```

Some of them are arabic: https://en.wikipedia.org/wiki/Eastern_Arabic_numerals

Others japanese, but my question is: is there support in `arrow` for parsing those and convert them to, for instance, ISO8601? Thanks!

@carles

**Comment by andrewelkins** [comment]
Not sure why it's acting like that. Doesn't seem to be a bug in arrow however.
