### ISSUE TITLE
Documentation feature request

### ISSUE THREAD

**Issue by Tjorriemorrie** [crsmithdev/arrow#153]
The documentation urgently require a section like momentjs' 'display'.

It's easy for me to create a new arrow datetime, but then I'm always stuck in searching (and not finding) how to output that to the different formats requirements of my system. What's the default value if just passed directly in as an arrow object. Can I get a native time or datetime object somehow? Why aren't all the format options shown (as a quick reference), i.e. now I have to browse around again to find it.

Really confusing and time wasting.

I really like this library, but outputting needs some clarification, thanks :)

**Comment by systemcatch** [comment]
i think the arrow docs are a lot better in this regard now, feel free to reopen if you disagree.
