### ISSUE TITLE
Make relative shifts more explicit?

### ISSUE THREAD

**Issue by nvie** [crsmithdev/arrow#158]
(Hey Chris, I absolutely _love_ this library. I have a very minimal library that makes dealing with dates and times easier ([times](https://github.com/nvie/times)), but I intend to change it to simply "wrap" arrow, and issue deprecation warnings, so people start adopting this library instead directly.)

---

Anyway... there was one thing about the API that confused me.

The following line will replace a "position" in the datetime:

``` python
a = arrow.get(2014, 8, 23, 11, 43, 00)
a.replace(hour=10)  # would change to 10:43:00
a.replace(hours=10)  # would change to 21:43:00
```

The mere difference of the singular/plural form is quite confusing and not obvious from the docs. Ideally, the `.replace()` method would not take the plural form (including the `weeks`). Those could be moved to a move natural `.shift()` method instead, which would communicate the relative nature of the operation as well. It can be used to shift forward and backward in time.

What do you think?
Vincent

**Comment by rsyring** [comment]
Arrow now has `shift()`, can this issue be closed?

**Comment by lucabezerra** [comment]
@crsmithdev First of all, thanks for the great lib!

I'm wondering, is there a scheduled date/time for `replace(hours=2)` (plural form) to be fully deprecated? I know the source code already says it's deprecated, but I'm wondering if/when is the method itself going to stop accepting parameters in the plural form. And if/when this day comes, any code that still uses it like that will simply stop working (makes more sense to me) or will it work as if I was using the parameters in the singular form (that would be terrible, silent failures)?

I haven't found any info about this around, not sure if I didn't search for it properly. Any light about this would be really appreciated. Thanks!

**Comment by Syeberman** [comment]
@lucabezerra We don't have a firm date set out (IMO we'll remove deprecated features with our first 1.0 release), but yes these parameters will be fully deleted from `replace`, which will mean all code that continues to use them will break.
