### ISSUE TITLE
Set timezones on new arrows cleanly

### ISSUE THREAD

**Issue by David-OConnor** [crsmithdev/arrow#159]
Current syntax: 

arrow.Arrow(1999, 9, 9, hour=9, minute=30,  tzinfo=dateutil.tz.gettz('US/Eastern'))

Desired syntax:
arrow.Arrow(1999, 9, 9, hour=9, minute=30,  tz='US/Eastern')

**Comment by andrewelkins** [comment]
Sorry, we're not going to change the syntax.
