### ISSUE TITLE
Does the library handle unix epoch conversion?

### ISSUE THREAD

**Issue by geekpete** [crsmithdev/arrow#175]
eg:
http://www.epochconverter.com/

**Comment by chidg** [comment]
It appears to: 
http://crsmithdev.com/arrow/#creation

>Create from timestamps (ints or floats, or strings that convert to a float):
```python
>>>> arrow.get(1367900664)
<Arrow [2013-05-07T04:24:24+00:00]>

>>>> arrow.get('1367900664')
<Arrow [2013-05-07T04:24:24+00:00]>

>>>> arrow.get(1367900664.152325)
<Arrow [2013-05-07T04:24:24.152325+00:00]>

>>>> arrow.get('1367900664.152325')
<Arrow [2013-05-07T04:24:24.152325+00:00]>
```

**Comment by geekpete** [comment]
Hey Thanks!

This is what I was looking for.

That's how to go from an epoch string to an Arrow object, so now trying to see if there's a way to go from Arrow back to epoch.

If this is done via the .format() then where do I find the detail of what possible values there are for the "fmt" variable?

Also there's no mention of the word "epoch" anywhere in the documentation, is there another name I might search for this with?

Cheers.

**Comment by geekpete** [comment]
Ah so "timestamp" is what I was after.

As per:

```python
>>> test = arrow.get(1367900664.152325)
>>> test
<Arrow [2013-05-07T04:24:24.152325+00:00]>
>>> test.timestamp
```
So maybe a quick mention in the documentation wherever timestamp is listed a note that mentions this is aka epoch or unix time.

Might be overkill I guess, but removing any confusion or doubt surely helps?

**Comment by andrewelkins** [comment]
That seems like a fine idea. If you submit a pull request I'll review it.
