### ISSUE TITLE
Unable to parse From field on email

### ISSUE THREAD

**Issue by brooksc** [crsmithdev/arrow#176]
I'm trying to parse a email date format (from gmail) and occasionally I see a date with GMT at the end.  I can't find a way to parse this -- Z and ZZ both fail.

Here's an example:

> > > import arrow
> > > d = 'Fri, 07 Nov 2014 18:09:57 GMT'
> > > arrow.get(d, 'ddd, D MMM YYYY HH:mm:ss ZZ')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Volumes/HD/home/brooksc/.virtualenv/default/lib/python2.7/site-packages/arrow/api.py", line 23, in get
> > >     return _factory.get(_args, *_kwargs)
> > >   File "/Volumes/HD/home/brooksc/.virtualenv/default/lib/python2.7/site-packages/arrow/factory.py", line 186, in get
> > >     dt = parser.DateTimeParser(locale).parse(args[0], args[1])
> > >   File "/Volumes/HD/home/brooksc/.virtualenv/default/lib/python2.7/site-packages/arrow/parser.py", line 135, in parse
> > >     raise ParserError('Failed to match token \'{0}\' when parsing \'{1}\''.format(token, original_string))
> > > arrow.parser.ParserError: Failed to match token 'ZZ' when parsing 'Fri, 07 Nov 2014 18:09:57 GMT'
> > > arrow.get(d, 'ddd, D MMM YYYY HH:mm:ss Z')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Volumes/HD/home/brooksc/.virtualenv/default/lib/python2.7/site-packages/arrow/api.py", line 23, in get
> > >     return _factory.get(_args, *_kwargs)
> > >   File "/Volumes/HD/home/brooksc/.virtualenv/default/lib/python2.7/site-packages/arrow/factory.py", line 186, in get
> > >     dt = parser.DateTimeParser(locale).parse(args[0], args[1])
> > >   File "/Volumes/HD/home/brooksc/.virtualenv/default/lib/python2.7/site-packages/arrow/parser.py", line 135, in parse
> > >     raise ParserError('Failed to match token \'{0}\' when parsing \'{1}\''.format(token, original_string))
> > > arrow.parser.ParserError: Failed to match token 'Z' when parsing 'Fri, 07 Nov 2014 18:09:57 GMT'

**Comment by andrewelkins** [comment]
Can it just be ignored?

**Comment by systemcatch** [comment]
With the addition of the ZZZ token this sting can now be parsed.

```shell
>>> d = 'Fri, 07 Nov 2014 18:09:57 GMT'
>>> arrow.get(d, 'ddd, D MMM YYYY HH:mm:ss ZZZ')
<Arrow [2014-11-07T18:09:57+00:00]>
```
