### ISSUE TITLE
RFC3339 format

### ISSUE THREAD

**Issue by jcelliott** [crsmithdev/arrow#180]
Is there an easy way to get an RFC3339 formatted time?

**Comment by andrewelkins** [comment]
```
>>> import arrow
>>> utc = arrow.utcnow()
>>> utc
<Arrow [2013-05-11T21:23:58.970460+00:00]>

>>> local.format('YYYY-MM-DDTHH:mm:ssZZ')
'2013-05-11 13:23:58 -07:00'
```

**Comment by jcelliott** [comment]
Hmm... This was long enough ago that I don't remember why I opened it.

    >>> import arrow
    >>> str(arrow.utcnow())
    '2015-07-10T22:18:55.951382+00:00'

Seems to work fine.

**Comment by andrewelkins** [comment]
:+1:

**Comment by andrewelkins** [comment]
Sorry it took me so long to respond!
