### ISSUE TITLE
humanize returns "in 1 months"

### ISSUE THREAD

**Issue by abemusic** [crsmithdev/arrow#182]
``` python
now = arrow.get('2014-12-11')
jan30 = arrow.get('2015-01-30')
jan30.humanize(now)
u'in 1 months'
```

I'm looking at the logic now for bucketing the time in seconds. The value that each conditional is checking against is supposed to be in seconds, but seem to be somewhat arbitrarily chosen to pad the humanized representation a bit. The particular diff in seconds from above is `4320000` and the conditional logic follows:
- < 10 = just now
- < 45 = in seconds
- < 90 = in a minute
- ...
- < 3888000 = 'in a month'
- < 29808000 = 'in x months'
- ...

In this case I fall into the 'in x months' bucket, which calculates x=1 and the representation is thrown off. I think in the buckets where a specific amount of time is being calculated, if we don't want to change the conditional values we should at least check the edge case of calculating one of that particular bucket and return the appropriate output from the `locale.describe`. In my case it would be 'month' instead of 'months'.

Hopefully that made sense :)

**Comment by andrewelkins** [comment]
Agreed on using the locale, care to make a PR to address it?
