### ISSUE TITLE
 .get() does not handle multiple spaces in date strings.

### ISSUE THREAD

**Issue by wsw70** [crsmithdev/arrow#188]
In the following string: `Mon Sep  8 23:07:39 2014` the day of the month (`8` in that case) is set to display on a fixed amount of spaces. In other words, the string `Mon Sep 19 23:07:39 2014` would have one space between `Sep` and `19`, while in the first example there are two spaces between `Sep` and `8`.

In such case 

```
dateformat = "ddd MMM DD HH:mm:ss YYYY"
start_epoch = arrow.get(date_string, dateformat).timestamp
```

(where `date_string` holds the date) raises the exception

```
ParserError: Failed to match token 'YYYY' when parsing 'Mon Sep  8 16:41:45 2014'
```

I think that the format should be universal and not take into account multiple spaces (the issue of a fixed field length is common). A solution could be to do a  `' '.join(date_string.split())` reformatting upon receiving the string. I even tried to fix this in the code and submit a pull request but, boy, the code is beyond my reach :)

**Comment by andrewelkins** [comment]
I don't think this is something arrow should handle. You're specifying DD so it expects it to be 0 padded. You're providing a date string that doesn't match the formatting your expecting. So it fails correctly.

**Comment by wsw70** [comment]
Well in that case what should be the formatting string in that case? The day is not zero padded but has a fixed length ('19' vs ' 8' - note the space)

**Comment by andrewelkins** [comment]
I understand the issue but that's a non-stand way to format a date. Does datetime/calendar/pytz handle that?

I think the work around for you is to remove the extra space and use something like 
```python
dateformat = "ddd MMM DD HH:mm:ss YYYY"
start_epoch = arrow.get(date_string.replace("  ", " "), dateformat).timestamp
```
The date should then work as it'll handle the single digit with one space. This isn't something we would want to add to arrow as it's really just covering up an error in the formatting.

You could send dates like:
```
Mon Sep 8 23:07:39 2014
Mon Sep 08 23:07:39 2014
```
But not
```
Mon Sep  8 23:07:39 2014
Mon Sep           8          23:07:39         2014
```

**Comment by wsw70** [comment]
Thank you Andrew for following up. What I meant to say is that one can pass a format to handle all non standard dates and the only case which would not be covered is a fixed width field, padded with spaces. Padding with zeros is supported, so why not fixed length?

I did find the solution in my case (`' '.join(date_string.split())`, which gets rid of multiple spaces), just thought that this could be an evolution for `arrow`.

**Comment by andrewelkins** [comment]
Syslog output is a perfectly valid use case. I think we would need a different letter to cover that instance instead of using DD to cover zero padded and also space padded.

**Comment by wsw70** [comment]
Since `DD` vs. `D` is quite standard I would leave it as it and just remove multiple spaces.

A format with one space in lieu of many will be backward compatible (`13 Jan 2015` handled by `DD MMM YYYY` will work as before, as well as `13    Jan      2015` with the same date format string) so 
I believe that just running the date to be parsed (say, `date_string`) by `' '.join(date_string.split())` will do the trick:
```
In [1]: date_string = '13    Jan      2015'

In [2]: ' '.join(date_string.split())
Out[2]: '13 Jan 2015'
```

**Comment by kdeldycke** [comment]
:+1:

Arrow should be able to parse dates with multiple spaces. It's not that hard to normalize spaces before feeding it to the `.get()` date parser with @wsw70's patch.

**Comment by andrewelkins** [comment]
You're specifying a format, arrow expects it to be in that format. If there's a incorrectly formatted input I think that should be handled before arrow gets it. Are there other date/time libraries that do this magic removal of spaces? If someone wants to create a pull request with this fix I will take a look at it. I want to see if there's any performance impact in doing this manipulation.

**Comment by wsw70** [comment]
**Note**: I just realized that I gave a wrong example in my initial post - I used `DD` instead of `D`. I am of course  not talking about 0-padded stings. The discussion further on seems to have taken note of that.

The thing is that one cannot specify a format with fixed width fields. This is not an incorrect format, this is one of the available ones (`syslog` as I mentioned above is one of them).
I do not know about other time libraries, I now exclusively use `arrow` :). The only thing I want to highlight here is that it is not possible to provide arrow the right format for fixed-length fields.

As for the performance, I did a test:

```
$ python -m timeit -n 100000 -s 'import arrow' 'arrow.get(" ".join("Mon Sep  8 23:07:39 2014".split()), "ddd MMM D HH:mm:ss YYYY")'
100000 loops, best of 3: 56 usec per loop

$ python -m timeit -n 100000 -s 'import arrow' 'arrow.get("Mon Sep 8 23:07:39 2014", "ddd MMM D HH:mm:ss YYYY")'
100000 loops, best of 3: 55.3 usec per loop
```

This means that there is an average 1.25% of time execution increase

**Comment by jadchaar** [comment]
Hey @wsw70, for now you can escape regex characters as follows to get this to work: `arrow.get("Mon Sep  08 16:41:45 2014", r"ddd[\s+]MMM[\s+]DD[\s+]HH:mm:ss[\s+]YYYY")`.

@systemcatch and I are discussing whether or not to add input sanitization as a standard feature.

**Comment by wsw70** [comment]
@jadchaar thanks for the follow-up.

I feel like it is less a sanity check than the capacity to handle a standard date format (standard in the sense that it is output by a common service such as `syslog`)

**Comment by jadchaar** [comment]
@wsw70 thanks for your feedback. The only issue we see with automatically formatting inputs is that what if someone wanted a format string with multiple spaces in it? E.g. `YYYY   MM`. Then, if we automatically replace the spaces in an input string (e.g.`2016      05`), then the format will break since it requires 3 spaces.

How would you envision an automatic handling of spaces?

**Comment by wsw70** [comment]
Yes, this is why I think that having an extra symbol for "number with a leading space when < 10" would be the solution. 

Let's say that this symbol is F (for the month). In that case the template

    ddd F DD HH:mm:ss YYYY

would cover both the case of `Mon Sep  8 16:41:45 2014` and `Mon Sep 12 16:41:45 2014`.

**Comment by jadchaar** [comment]
That is an interesting proposition, but in the meantime, [escaping is the way to go](https://arrow.readthedocs.io/en/latest/#escaping-formats).

**Comment by jadchaar** [comment]
We will re-open this in the future if we decide to implement extra tokens :).
