### ISSUE TITLE
is it possible to load an isocalendar tuple into an arrow instance?

### ISSUE THREAD

**Issue by kurttheviking** [crsmithdev/arrow#189]
Currently, arrow conveniently provides:

```
>>> import arrow
>>> d = arrow.utcnow().isocalendar()
>>> d
(2015, 1, 1)
```

However, I am not sure if it is possible to load that tuple `d` later using `arrow.get()` &ndash; is there a format specification I am missing? For example:

```
>>> d_arrow = arrow.get(d, 'isocalendar')
```

If not, I am happy to help with a PR for a target spec.

**Comment by andrewelkins** [comment]
Correct it currently can't handle a tuple, it expects a string. If you're still looking to make a PR, I'd start by looking at `arrow/factory.py`

**Comment by kurttheviking** [comment]
ok great thank you; ill take a look

**Comment by systemcatch** [comment]
https://stackoverflow.com/questions/304256/whats-the-best-way-to-find-the-inverse-of-datetime-isocalendar for some related discussion on this topic.

Simple approach is to convert the tuple to a date then pass it to fromdate().

**Comment by jadchaar** [comment]
@systemcatch your PR #670 seems to have tackled this. We good to close this now?

**Comment by systemcatch** [comment]
We're good, I'll close this.
