### ISSUE TITLE
Feature: add and substract operators?

### ISSUE THREAD

**Issue by ifmihai** [crsmithdev/arrow#197]
Just bumped into arrow. 
really great initiative.

I was wondering if adding and substracting are planned in the (near) future.

For example

```python
dt = arrow.utcnow()
dt += 6
dt += '5 days'

# as for substraction or difference, it would be nice to have something like
arrow.period(dt1, dt2, frame='5 min')  # to have number of periods between 2 dates
```

**Comment by OrangeTux** [comment]
Are you aware of [Arrow.replace()][1] and [Arrow.span_range][2]? 

    >>> arw.replace(weeks=+3)
    <Arrow [2013-06-02T03:29:35.334214+00:00]>

    >>> start = datetime(2013, 5, 5, 12, 30)
    >>> end = datetime(2013, 5, 5, 17, 15)
    >>> for r in arrow.Arrow.span_range('hour', start, end):
    ...        print r
    ...
    (<Arrow [2013-05-05T12:00:00+00:00]>, <Arrow [2013-05-05T12:59:59.999999+00:00]>)
    (<Arrow [2013-05-05T13:00:00+00:00]>, <Arrow [2013-05-05T13:59:59.999999+00:00]>)
    (<Arrow [2013-05-05T14:00:00+00:00]>, <Arrow [2013-05-05T14:59:59.999999+00:00]>)
    (<Arrow [2013-05-05T15:00:00+00:00]>, <Arrow [2013-05-05T15:59:59.999999+00:00]>)
    (<Arrow [2013-05-05T16:00:00+00:00]>, <Arrow [2013-05-05T16:59:59.999999+00:00]>)

[1]:http://crsmithdev.com/arrow/#replace-shift
[2]:http://crsmithdev.com/arrow/#ranges-spans

**Comment by ifmihai** [comment]
i was just saying how flow of thought happens, at least in my case.

I doubt, though, users think in terms in replace or span_range when:
1.  they want to add or substract some units of time from an arrow datetime (examples above)
2. they want ```dt1 = dt + '5 hours' ```

for me, nothing beats direct datetime operations.

**Comment by OrangeTux** [comment]
I won't vote for doing the same things in multiple ways. I think that's confusing.

**Comment by andrewelkins** [comment]
It's an interesting thought. I personally like the idea, but I won't be putting it in arrow simply because it can already be done in another way. I've been apart of other projects that start down this path and it because a maintenance nightmare.
