### ISSUE TITLE
Arrow 0.5.0, parsing 20141029T080600 fails

### ISSUE THREAD

**Issue by ztane** [crsmithdev/arrow#198]
`arrow.get('20141029T080600')` fails, isn't arrow supposed to parse that properly?

**Comment by andrewelkins** [comment]
Not by default, you need to specify the format. Something like:

```
arrow.get('20141029T080600', 'YYYYMMDDTHHmmss')
```

**Comment by everilae** [comment]
Perfectly valid ISO8601 and not even that uncommon, seems like a missed arrow.
