### ISSUE TITLE
Upload arrow 0.5.2. to PyPI

### ISSUE THREAD

**Issue by Yasumoto** [crsmithdev/arrow#199]
Looks like the [latest release published to PyPI is 0.4.6](https://pypi.python.org/pypi/arrow/0.4.6), any chance the package maintainers can upload the latest dist?

**Comment by andrewelkins** [comment]
Can do.

**Comment by Yasumoto** [comment]
That'd be rad, thanks @andrewelkins ! :+1:

**Comment by pypingou** [comment]
Could you do 0.5.3 while at it? :)

**Comment by pypingou** [comment]
https://pypi.python.org/pypi/arrow

``python setup.py sdist upload``? :smile:

**Comment by andrewelkins** [comment]
Soon. Just updated the version and such. It'll be pushed today. Sorry for the delay.

**Comment by Yasumoto** [comment]
No worries, thanks for keeping everyone up to date :smiley:

**Comment by ralphbean** [comment]
I see 0.5.4 made it up there today.  This can probably be closed.  :)

**Comment by andrewelkins** [comment]
Yep
