### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by pc10201** [crsmithdev/arrow#203]
import arrow
today=arrow.utcnow().format('YYYYMMDD Hmm')
minutes=arrow.get(today,'YYYYMMDD Hmm')
print minutes

File "D:\Python27\lib\site-packages\arrow\api.py", line 23, in get
    return _factory.get(_args, *_kwargs)
  File "D:\Python27\lib\site-packages\arrow\factory.py", line 197, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "D:\Python27\lib\site-packages\arrow\parser.py", line 131, in parse
    raise ParserError('Failed to match token \'{0}\' when parsing \'{1}\''.format(token, original_string))

version:0.5.4

but the code below is OK

import arrow
today=arrow.utcnow().format('YYYYMMDD H:mm')
minutes=arrow.get(today,'YYYYMMDD H:mm')
print minutes

**Comment by mlew** [comment]
This issue seems to be resolved in 0.6.0. Tested using Python 2.7.10 on OSX 10.10.4

I suggest closing this bug.
