### ISSUE TITLE
UnicodeDecodeError  long_description=open('README.rst').read(),

### ISSUE THREAD

**Issue by rubensgomes** [crsmithdev/arrow#208]
HI,  

I am running into the following problem when installing arrow using pip in Python 3.4.3.

(venv) [wsgi@vps venv]$ python -V
Python 3.4.3
(venv) [wsgi@vps venv]$ pip -V
pip 6.0.8 from /home/wsgi/flaskapis/venv/lib/python3.4/site-packages (python 3.4)
(venv) [wsgi@vps venv]$ pip -v install arrow
Collecting arrow
  Getting page https://pypi.python.org/simple/arrow/
  URLs to search for versions for arrow:
  * https://pypi.python.org/simple/arrow/
  Getting page https://pypi.python.org/simple/arrow/
  Analyzing links from page https://pypi.python.org/simple/arrow/
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.1.1.tar.gz#md5=359f36ace04fdee41f551cf1012c0832 (from https://pypi.python.org/simple/arrow/), version: 0.1.1
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.1.2.tar.gz#md5=c3c195c9b5f7753671f15072138455ae (from https://pypi.python.org/simple/arrow/), version: 0.1.2
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.1.3.tar.gz#md5=8aaace219714230ff874a0677652bc4f (from https://pypi.python.org/simple/arrow/), version: 0.1.3
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.1.4.tar.gz#md5=dfc6d1f438ccd40d5b4b77efb04f4cc9 (from https://pypi.python.org/simple/arrow/), version: 0.1.4
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.1.5.tar.gz#md5=a74c113613b2dd99640fae59d9da6e90 (from https://pypi.python.org/simple/arrow/), version: 0.1.5
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.1.6.tar.gz#md5=de16da2a01454750bd7ac236fdd39f83 (from https://pypi.python.org/simple/arrow/), version: 0.1.6
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.1.tar.gz#md5=9e83e0ea8d4e9f585cda8dd29d0176a4 (from https://pypi.python.org/simple/arrow/), version: 0.1
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.2.0.tar.gz#md5=875ee5e21b61f88e92bd5379a3d2dc97 (from https://pypi.python.org/simple/arrow/), version: 0.2.0
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.2.1.tar.gz#md5=683e270fa139f4c969e5e36ed3428d3b (from https://pypi.python.org/simple/arrow/), version: 0.2.1
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.3.0.tar.gz#md5=43048c10fa54b4dace276e9b2803619e (from https://pypi.python.org/simple/arrow/), version: 0.3.0
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.3.1.tar.gz#md5=c34127ae9da57e6dbdd233a817d10773 (from https://pypi.python.org/simple/arrow/), version: 0.3.1
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.3.2.tar.gz#md5=9a4d35818ca5fd9d7be50512976f3feb (from https://pypi.python.org/simple/arrow/), version: 0.3.2
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.3.3.tar.gz#md5=74042d50f253eafd69b94cea3cc9494f (from https://pypi.python.org/simple/arrow/), version: 0.3.3
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.3.4.tar.gz#md5=e560c73a1c1f0fb90a124d8ba1920232 (from https://pypi.python.org/simple/arrow/), version: 0.3.4
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.3.5.tar.gz#md5=b6ffcc19a8f5a67fb8d18e3b80878137 (from https://pypi.python.org/simple/arrow/), version: 0.3.5
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.4.0.tar.gz#md5=a3275a1fd50c94a983b6fe949d5c1082 (from https://pypi.python.org/simple/arrow/), version: 0.4.0
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.4.1.tar.gz#md5=bbcd88f2105d4644730d2199d4e29953 (from https://pypi.python.org/simple/arrow/), version: 0.4.1
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.4.2.tar.gz#md5=5caa8442fd3a84a5ad0155a1f626ef1d (from https://pypi.python.org/simple/arrow/), version: 0.4.2
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.4.3.tar.gz#md5=0caed6c28e4c48582bd4556aaefba352 (from https://pypi.python.org/simple/arrow/), version: 0.4.3
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.4.4.tar.gz#md5=8ea354c168fdf0a65a048ac665168d68 (from https://pypi.python.org/simple/arrow/), version: 0.4.4
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.4.6.tar.gz#md5=e073bdf6a3852558adcaeb42aeba2296 (from https://pypi.python.org/simple/arrow/), version: 0.4.6
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.5.0.tar.gz#md5=fb8592d3097d23bcf550810ade774346 (from https://pypi.python.org/simple/arrow/), version: 0.5.0
    Found link https://pypi.python.org/packages/source/a/arrow/arrow-0.5.4.tar.gz#md5=92c69f04a05c5fb03d43597833dcd5fb (from https://pypi.python.org/simple/arrow/), version: 0.5.4
  Using version 0.5.4 (newest of versions: 0.5.4, 0.5.0, 0.4.6, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1)
  Using cached arrow-0.5.4.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/a/arrow/arrow-0.5.4.tar.gz#md5=92c69f04a05c5fb03d43597833dcd5fb (from https://pypi.python.org/simple/arrow/)
  Running setup.py (path:/tmp/pip-build-9_oizab7/arrow/setup.py) egg_info for package arrow
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-9_oizab7/arrow/setup.py", line 31, in <module>
        long_description=open('README.rst').read(),
      File "/opt/python3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 2974: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-9_oizab7/arrow/setup.py", line 31, in <module>

        long_description=open('README.rst').read(),

      File "/opt/python3.4/lib/python3.4/encodings/ascii.py", line 26, in decode

        return codecs.ascii_decode(input, self.errors)[0]

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 2974: ordinal not in range(128)

    ----------------------------------------
    Cleaning up...
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9_oizab7/arrow
    Exception information:
    Traceback (most recent call last):
      File "/home/wsgi/flaskapis/venv/lib/python3.4/site-packages/pip/basecommand.py", line 232, in main
        status = self.run(options, args)
      File "/home/wsgi/flaskapis/venv/lib/python3.4/site-packages/pip/commands/install.py", line 339, in run
        requirement_set.prepare_files(finder)
      File "/home/wsgi/flaskapis/venv/lib/python3.4/site-packages/pip/req/req_set.py", line 385, in prepare_files
        req_to_install.run_egg_info()
      File "/home/wsgi/flaskapis/venv/lib/python3.4/site-packages/pip/req/req_install.py", line 358, in run_egg_info
        command_desc='python setup.py egg_info')
      File "/home/wsgi/flaskapis/venv/lib/python3.4/site-packages/pip/utils/__init__.py", line 749, in call_subprocess
        % (command_desc, proc.returncode, cwd))
    pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9_oizab7/arrow

(venv) [wsgi@vps venv]$

**Comment by rubensgomes** [comment]
The fix for the issue with the "long_description=open('README.rst').read()," in the setup.py that causes the "UnicodeDecodeError" was fixed on my CentOS 7 Linux VPS by changing the user's environment locale setting to en_US.utf8 as follows:

[wsgi@vps ~]$ locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=

**Comment by ulope** [comment]
I would argue that this still is a bug. Instead of using regular `open` it would be much safer to use `codecs.open` with an explicit encoding declaration.
