### ISSUE TITLE
Support for years before 1 and after 9999

### ISSUE THREAD

**Issue by sgillies** [crsmithdev/arrow#210]
I'm a Python programmer who works on archaeological datasets and would like to use Arrow. 

Currently it isn't possible to construct Arrow dates before the year 1.

```python
>>> arrow.Arrow(1, 1, 1)
<Arrow [0001-01-01T00:00:00+00:00]>
>>> arrow.Arrow(0, 1, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/seang/envs/scraping/lib/python2.7/site-packages/arrow/arrow.py", line 57, in __init__
    microsecond, tzinfo)
ValueError: year is out of range
```

or after 9999.

```python
>>> arrow.Arrow(9999, 1, 1)
<Arrow [9999-01-01T00:00:00+00:00]>
>>> arrow.Arrow(10000, 1, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/seang/envs/scraping/lib/python2.7/site-packages/arrow/arrow.py", line 57, in __init__
    microsecond, tzinfo)
ValueError: year is out of range
```

Are you willing to accept a PR that would add support for dates beyond [1, 9999]? Do you see any blockers in Python's standard lib for doing this?

**Comment by AbsoluteMSTR** [comment]
I don't see this is possible since python's datetime module is only supports year 1-9999. Arrow would need to rely on its own datetime module instead of wrapping around python's datetime.

**Comment by andrewelkins** [comment]
Agreed with @AbsoluteMSTR we're bound to what datetime supports. https://docs.python.org/2/library/datetime.html#datetime.MINYEAR

If there's an easy fix I'm not seeing, we'd be open to a pull request. That said, if it's converting to a custom datetime lib, we likely wouldn't want to do that as we'd then have to maintain it.
