### ISSUE TITLE
0-based vs 1-based month_names and day_names in locales.py

### ISSUE THREAD

**Issue by nikhilkulkarnisr** [crsmithdev/arrow#213]
In all locales except CzechLocale, the arrays for month names and day names are 1-based (by forcing array[0] = ''). I assume that this is done because datetime.isoweekday starts with 1 and not 0. (https://docs.python.org/2/library/datetime.html#datetime.date.isocalendar). Why does Czech locale behaves differently? This could be confusing to some.

**Comment by andrewelkins** [comment]
Can you provide code to reproduce? I can't reproduce.
