### ISSUE TITLE
adjusting by an offset is easily confused with adjusting a specific part of a date

### ISSUE THREAD

**Issue by mozbhearsum** [crsmithdev/arrow#220]
Someone pointed out to me today that having such similarly named keywords in the .replace() API has the potential for some confusion. Eg: "minute" and "minutes" where the former changes the minute the value given, while the latter adjusts by an offset. This means that very similar looking (and easy to typo) calls can do vastly different things:
arrow.now().replace(month=5)
arrow.now().replace(months=5)

This person suggested that a different method for offset adjustments might be better. Eg:
arrow.now().shift(months=5)

**Comment by andrewelkins** [comment]
I like this a lot. Can you make a PR for this?

**Comment by rsyring** [comment]
can this be closed now that `shift()` is a method?

**Comment by systemcatch** [comment]
It can be! :hammer:
