### ISSUE TITLE
Incorrect results subtracting Arrow instances

### ISSUE THREAD

**Issue by paulfurber** [crsmithdev/arrow#223]
Hey,
Ubuntu 14.04 LTS, Python 2.7.6 and the latest build of Arrow from github. When I subtract one datetime from another in Arrow, I get bizarre results:

    import arrow
    start = arrow.get("2015-05-16 20:30:00", "YYYY-MM-DD HH:mm:ss")
    now = arrow.now()
    now - start
    >> datetime.timedelta(-1, 80197, 439524)
    (now - start).seconds
    >> 80197

negative one day and 80000 seconds? It should be postitive 20 minutes or so. Built-in datetime gives the right answer. 

    from datetime import datetime
    start = datetime.strptime('2015-05-16 20:30:00', '%Y-%m-%d %H:%M:%S')
    now = datetime.now()
    (now - start).seconds
    >> 1272

**Comment by dgilland** [comment]
If you compare the output of `now.tzinfo` and `start.tzinfo`, you'll notice that `now` is set to `tzlocal()` while `start` is set to `tzutc()`. When using the `datetime` module, `datetime.now().tzinfo` and `start.tzinfo` are both `None`.

There's `arrow.utcnow()` which can be used in your first example which will put both `now` and `start` in UTC.

**Comment by paulfurber** [comment]
Argh - I forgot that now() would be set to tzlocal. Thank you.
