### ISSUE TITLE
Installation fails on certain locales

### ISSUE THREAD

**Issue by homeworkprod** [crsmithdev/arrow#224]
Trying to install Arrow 0.5.4 fails on some locales:

```
$ LANG=C pip install Arrow
Downloading/unpacking Arrow
  Downloading arrow-0.5.4.tar.gz (81kB): 81kB downloaded
  Running setup.py (path:/home/user/project/venv/build/Arrow/setup.py) egg_info for package Arrow
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/user/project/venv/build/Arrow/setup.py", line 31, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 2974: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/user/project/venv/build/Arrow/setup.py", line 31, in <module>

    long_description=open('README.rst').read(),

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 2974: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/user/project/venv/build/Arrow
Storing debug log for failure in /home/user/.pip/pip.log
```

This seems to be caused by the README containing Korean symbols.

It's especially annoying as tox doesn't generally pass environment variables to subprocesses (anymore?), so pip isn't executed with the explicitly specified `LANG` as in `LANG=C.UTF-8 tox` and fails as seen above.

IMHO the installation should work regardless of the current locale.

The obvious fix would be removal of the "offending" characters from the README (and re-adding the example at some other place in the docs; one that doesn't affect installation).

**Comment by homeworkprod** [comment]
Also see https://github.com/ekalinin/nodeenv/issues/123 for a similar issue, and https://bitbucket.org/hpk42/tox/issue/247/pass-through-lang-environment-variable-by for a bug report against tox.

**Comment by homeworkprod** [comment]
Maybe just adding the encoding line to the setup file might help already (see https://github.com/ekalinin/nodeenv/commit/b38356dcd3d26f92cd262fa5854043edea8e087c).

**Comment by kdeldycke** [comment]
Looks like this issue is fixed since #202, but arrow wasn't released on PyPi since then.

**Comment by leafonsword** [comment]
I have the same problem trying to install Arrow 0.5.4 in Python 3.4~

**Comment by vmalloc** [comment]
Any idea when this would be fixed? It's preventing us from using the latest Arrow in our environments...

**Comment by leafonsword** [comment]
@vmalloc 
install from github other than from pypi~

**Comment by vmalloc** [comment]
Yeah, unfortunately this isn't always an option...

**Comment by jmagnusson** [comment]
Like @vmalloc says it's not always reasonable to do so. Depending on releases only found on GitHub in your `setup.py` requires the use of `pip install --find-links`, which most people aren't aware of.

**Comment by vmalloc** [comment]
It's not only that. Installing from Github exposes your installs to occasional breakage and mishaps, and this is not always compatible with `setup.py` requirements.

**Comment by jmagnusson** [comment]
Not trying to hi-jack this thread or anything but just out of curiousness, what problems might those be? @vmalloc

**Comment by vmalloc** [comment]
@jmagnusson Like shipping code that relies on a library that relies on arrow. The intermediate library needs to include requirements in its `setup.py` and cannot make assumptions about how it is to be installed.

**Comment by jmagnusson** [comment]
Yeah I've noticed that one as well... Do we have any issue on https://github.com/pypa/pip where this can be discussed? I really miss this feature from `npm`.

**Comment by vmalloc** [comment]
There have been a lot of discussions about this, but for now this is not an option. Some folks still install code using `pythons setup.py install` or other methods (buildout, setuptools, and others as well)

**Comment by andrewelkins** [comment]
Chris will be doing a publish to pypi shortly.
