### ISSUE TITLE
replace(week=n) should work

### ISSUE THREAD

**Issue by gramster** [crsmithdev/arrow#233]
I was thinking of writing a Python library to manipulate dates but then I found Arrow, and the replace() method largely implements what I want. However, I had a couple of features I wanted/needed that Arrow seems to be lacking. 

One of these is setting a specific week. I want week=1 (or maybe week=0) to set the day to the first Sunday of the month (in locales where Sunday is the first day of the week; adjust accordingly). Similarly, week=-1 should set to the last Sunday of the month.

(Related to this, I haven't checked yet but I guess you can't do something like day=-1 which in my case I wanted to be the last day of the month (it's easy enough to do with replace(months=1).replace(day=1).replace(days=-n) but that is quite verbose. I can open a separate issue for that if its (i) missing and (ii) considered useful. Finally, I have a similar need for day-of-week functionality which I planned to do with TLAs, like fri=3 for the third Friday of the month or sun=-2 for the second last Sunday of the month. This is more tricky with localization though).

**Comment by andrewelkins** [comment]
If you want to create a PR I'd love to take a look and merge.

**Comment by andrewelkins** [comment]
This should be addressed by one of the latest PRs. Week isn't implemented but the rest are.
