### ISSUE TITLE
arrow.get() converts bool types (False and True) incorrectly

### ISSUE THREAD

**Issue by trcarden** [crsmithdev/arrow#238]
``` python
In [1]: import arrow

In [2]: arrow.get(False)
Out[2]: <Arrow [1970-01-01T00:00:00+00:00]>

In [3]: arrow.get(True)
Out[3]: <Arrow [1970-01-01T00:00:01+00:00]>
```

This is because of the cast of the input to a float. Float type casts booleans to their underlying numeric representations. However i don't think true bool types should be interpreted as valid date/times.

**Comment by andrewelkins** [comment]
I think this is an edge case. Should it throw an exception instead?

**Comment by pcn** [comment]
:+1: to throwing a TypeError.

**Comment by trcarden** [comment]
I agree with a TypeError. If you really really want to use 0 and 1, use them instead
