### ISSUE TITLE
Cannot parse SQL Server DateTimeOffset formats

### ISSUE THREAD

**Issue by dagostinelli** [crsmithdev/arrow#245]
My project involves MS-SQL Server and pymssql to access it.

Arrow cannot parse these strings:

This is a datetimeoffset as seen in MS SQL Server. Arrow can't parse it.
2015-07-17 20:19:55.5934944 -05:00

Here is the same value as seen by pymssql.  Arrow can't parse it.
2015-07-17T20:19:55.5934944-05

Here is the first string modified slightly to try and make it work (but it doesn't) Arrow can't parse it.
2015-07-17T20:19:55.5934944-05:00

This works (because the length was shortened)  Arrow parsed it.
2015-07-17T20:19:55.593494-05:00

I was hoping for the 2nd format to work.

```
>> import arrow
>> arrow.get("2015-07-17T20:19:55.5934944-05")
arrow.parser.ParserError: Could not match input to any of [u'YYYY-MM-DDTHH:mm:ss.SSSSSSZ'] on '2015-07-17T20:19:55.5934944-05'
```

**Comment by andrewelkins** [comment]
That's not a default format. You'll need to specify the format for arrow to parse.

Something like:
```
arrow.get('2015-07-17 20:19:55.5934944 -05:00', 'YYYY-MM-DD HH:mm:ss.SSS ZZ')
```
[Further tokens documented here](https://arrow.readthedocs.org/en/latest/#tokens)

**Comment by dagostinelli** [comment]
(I thought arrow was trying to build up a collection of automatic parsers that can support a variety of slightly imperfect date time formats that are widely used out there.  That's why I sent these samples in.  The formats I sent are from MS SQL Server and pymssql which are widely used.   I realized that these 3 are not standard formats.  That's why the existing python libraries that I am already using had a problem with them.)

Is there a way to specify a variable length sub-second field? SQL Server sends back a high precision subsecond field.  I'd rather not have to specify that it is exactly always 7 digits wide though.

Thanks for building this library.

**Comment by andrewelkins** [comment]
Makes sense. We do for many ISO-8601 string and different ints, but those are not ones we considered. 

Is `2015-07-17T20:19:55.5934944-05` inparsable even when formatting is provided?

**Comment by dagostinelli** [comment]
It is imparsable.  Even with formatting.  Or at least, I can't find a pattern that fits.
