### ISSUE TITLE
Add xrange method

### ISSUE THREAD

**Issue by skitoo** [crsmithdev/arrow#251]
Can you add xrange method to arrow object ?
It's like range method but it return an iterator.

Thank you

**Comment by andrewelkins** [comment]
Would welcome a PR to do this

**Comment by pganssle** [comment]
@skitoo @andrewelkins Given that Python changed its semantics such that `range` returns an iterator now and `xrange` is deprecated, maybe it's worth just switching `range` to be an iterator (this would be a breaking change, so probably the best way to go is to gather together this with other breaking changes and make a 1.0 release).

Also, one possible thought on an option for the short term, you could provide a lazy-evaluated `_arrow_range` object that mimics list semantics, and on anything except iterating over it (slicing, appending, extending, etc), raise a `DeprecationWarning`, to warn people of the coming change.
