### ISSUE TITLE
Support ISO8601 format with nano second resolution

### ISSUE THREAD

**Issue by avishai-ish-shalom** [crsmithdev/arrow#262]
Elasticsearch returns date strings in ISO8601 format with nano second resolution which should have the format spec in arrow of: u'YYYY-MM-DDTHH:mm:ss.SSSSSSSSSZ' - however arrow only supports SSSSSS (microsecond resolution).

Alternatively, skipping some character will also resolve this, e.g. u'YYYY-MM-DDTHH:mm:ss.SSSSSS___Z' where '_' is a new token which only skips characters.

**Comment by bukzor** [comment]
I believe this is fixed in 0.9.0.
Please have a try.

**Comment by andrewelkins** [comment]
Closing. Please reopen if it is still an issue.
