### ISSUE TITLE
arrow.get("invalid date") does not raise an error

### ISSUE THREAD

**Issue by MarcoSulla** [crsmithdev/arrow#267]
> > > import arrow
> > > arrow.get("2015-06-31")
> > > <Arrow [2015-06-01T00:00:00+00:00]>

It should raise an error.

**Comment by balihoo-gens** [comment]
what is the deal with this? 
```
>>> arrow.get("3015-13-78")
<Arrow [3015-01-01T00:00:00+00:00]>
```

**Comment by andrewelkins** [comment]
Will be handled by #91
