### ISSUE TITLE
Confused parsing

### ISSUE THREAD

**Issue by lcgong** [crsmithdev/arrow#268]
The following parsing result is confused. In some conditions, it's really difficult to debug. If the given string can not be parsed right, it's better to raise a ParserError rather than to set a default value.

```
>>> arrow.get('2015-7-3')
<Arrow [2015-01-01T00:00:00+00:00]>

>>> arrow.get('2015-3-3')
<Arrow [2015-01-01T00:00:00+00:00]>
```

**Comment by arvindch** [comment]
You should probably pass the format to arrow, instead:

```
>>> arrow.get('2015-7-3', ['YYYY-M-D'])
<Arrow [2015-07-03T00:00:00+00:00]>
```

**Comment by andrewelkins** [comment]
Check out #91 it'll be handled there
