### ISSUE TITLE
replace error

### ISSUE THREAD

**Issue by novoxudonoser** [crsmithdev/arrow#272]
python 3 arrow 0.7.0 (pip latest)

What I do:

```
>>> a=arrow.utcnow()
>>> a
<Arrow [2015-10-10T23:32:20.344633+00:00]>
>>> a.replace(seconds=30)
<Arrow [2015-10-10T23:32:50.344633+00:00]>
```

What I expect:

```
<Arrow [2015-10-10T23:32:30.344633+00:00]>
```

Seconds was plused not replaced.

**Comment by arvindch** [comment]
Using plural time nouns will result in shifting instead of replacing, as per https://github.com/crsmithdev/arrow/blob/master/arrow/arrow.py#L381.

So, use `second` instead of `seconds`.

**Comment by philiptzou** [comment]
There's a pull-request related with this issue and it will solve the implicit problem: #276

**Comment by andrewelkins** [comment]
This was handled by a PR
