### ISSUE TITLE
Documentation of read the docs is outdated.

### ISSUE THREAD

**Issue by swistakm** [crsmithdev/arrow#279]
RTD: https://arrow.readthedocs.org/en/latest/

What is in the code: https://github.com/crsmithdev/arrow/blob/master/docs/index.rst

Among others RTD docs are missing footnotes and `Do` tokens in tokens table. Those were added somewhere around 0.5.4 release so at least few month ago.

Documentation footer says it is 0.4.4 version!

**Comment by guidj** [comment]
Yes, and the time parsing tokens seem to have changed

**Comment by ulope** [comment]
http://crsmithdev.com/arrow/ (which may or may not be the same as RTD) also shows version 0.4.4 and is the first hit on google for `arrow python`

**Comment by ulope** [comment]
Why was this closed? Both URLs still show version 0.4.4.

**Comment by andrewelkins** [comment]
Right you are, merging the fix now. Just need Chris to update the RTD

**Comment by andrewelkins** [comment]
Next release this will be fixed.

**Comment by ulope** [comment]
The footer on RTD still says `0.4.4`
