### ISSUE TITLE
Day of week parsing does not work

### ISSUE THREAD

**Issue by ColCarroll** [crsmithdev/arrow#281]
It seems like the following should work:
```
some_date = 'Wed 6 Jun 2007 23:13:53'
fmt = 'ddd D MMM YYYY HH:mm:ss'
arrow.get(some_date, fmt)
```
But it throws a `ParserError`.  Note that the parsing works without the day of the week, and `.format` handles things fine:

```
arrow.get(some_date[4:], fmt[4:]).format(fmt) == some_date  # True
```

**Comment by philiptzou** [comment]
I guess the 'ddd' is an extra information so `DateTimeParser` simply ignores it. Perhaps we could replace 'd', 'ddd' and 'dddd' with some placeholders in the parser regexp to keep consistency with `DateTimeFormatter`.

**Comment by jeffbr13** [comment]
Same issue here, it's [a documented token](http://crsmithdev.com/arrow/#tokens) so really shouldn't cause parse failures, even if it's just stubbed out for now because of the debatable usefulness of days-of-the-week.

**Comment by theotherp** [comment]
It works with 0.6.0 and fails with 0.7.0. It even fails parsing its own formatted date:

    import arrow
    pubdate = arrow.get().format("ddd, DD MMM YYYY HH:mm:ss Z")
    arrow.get(pubdate, "ddd, DD MMM YYYY HH:mm:ss Z")

throws

arrow.parser.ParserError: Failed to match 'ddd, (?P<DD>\d{2}) (?P<MMM>(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)) (?P<YYYY>\d{4}) (?P<HH>\d{2}):(?P<mm>\d{2}):(?P<ss>\d{2}) (?P<Z>[+\-]?\d{2}:?\d{2})' when parsing 'Sat, 09 Jan 2016 11:19:13 -0000'

**Comment by foxmask** [comment]
it seems that version 0.7.0 works only on windows.

```python
> python
Python 3.5.0 .... [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> date='Tue Feb 09 2016'
>>> arrow.get(date, 'ddd MMM DD YYYY')
<Arrow [2016-02-09T00:00:00+00:00]>
```
but not on Linux (at least : centos / debian / ubuntu)

**Comment by theotherp** [comment]
My example above doesn't even work in windows 10.
