### ISSUE TITLE
(not an issue) how to extend arrow?

### ISSUE THREAD

**Issue by wsw70** [crsmithdev/arrow#285]
Arrow is fantastic, I do not use anything else for date/time manipulations.

I now would like to expand it a bit, by adding a method for the `Arrow` object. I saw there was a [previous discussion](https://github.com/crsmithdev/arrow/issues/19) about a similar subject, and I tried a suggestion from there:

```python
import arrow
import arrow.arrow

class MyArrow(arrow.arrow.Arrow):
    def __init__(self, year, month, day, hour=0, minute=0, second=0, microsecond=0, tzinfo=None):
        super().__init__(year, month, day, hour=0, minute=0, second=0, microsecond=0, tzinfo=None)

    def nextday(self):
        print("tomorrow is {day}".format(day=self.replace(days=+1).day))

f = arrow.factory(MyArrow)
print(f.now())
print(f.now().nextday())
```

It does not work as `arrow.factory()` is not implemented. 

```
Traceback (most recent call last):
  File "C:/Users/yop/.PyCharm50/config/scratches/scratch_38", line 10, in <module>
    f = arrow.factory(MyArrow)
TypeError: 'module' object is not callable
```

Does that mean that the idea was implemented in another way? 

I am trying to wrap my head around the `ArrowFactory` and `Arrow` classes. My naive understanding is that calling `ArrowFactory().one_of_the_methods()` will return an `Arrow` object. In that case I do not understand how to solve the problem of
* creating my own `Arrow`class, with the relevant method
* creating my own `ArrowFactoryè class which inherits `Arrow` (from the docs)
* and have the capacity to use `get()`, `now()`, etc. which are methods of `ArrowFactory`

**Comment by philiptzou** [comment]
The `TypeError` is trying to tell that `arrow.factory` is an module so you can't call it directly. But apparently it failed haha.

```python
import arrow
import arrow.arrow

class MyArrow(arrow.arrow.Arrow):
    def __init__(self, year, month, day, hour=0, minute=0, second=0, microsecond=0, tzinfo=None):
        super().__init__(year, month, day, hour=0, minute=0, second=0, microsecond=0, tzinfo=None)

    def nextday(self):
        print("tomorrow is {day}".format(day=self.replace(days=+1).day))

f = arrow.factory.ArrowFactory(MyArrow)
print(f.now())
print(f.now().nextday())
```

This will work.

**Comment by wsw70** [comment]
@philiptzou thank you for the help and for the fully working example. It made my day.

The condescending comment  was not useful, I mentioned the error in the context of the linked example but you may have missed that obvious part.

**Comment by philiptzou** [comment]
@wsw70 If my words make you feel condescending I'm really sorry about that. My intention is to complain the ambiguous error message that comes with `TypeError` means nothing and no one can understand it. Unless you have been f***ed by that message before.

But it will be another long story if we want to make Python changing the message.

**Comment by wsw70** [comment]
No pb,  we're good :) And thanks for the working example.  I just now need to understand why `arrow.now()` correctly handles hours,  minutes and seconds, while `f.now()` does not,  setting them to 0. I know that these are the default values but why the day, month and year is correctly set is a mystery for me.

**Comment by philiptzou** [comment]
@wsw70 Perhaps you should not set "hour=0, minute=0, second=0, microsecond=0, tzinfo=None" in your constructor when calling `super().__init__`.
