### ISSUE TITLE
ISO8601 isn't supported. Suggest stop naming it in the docs or fix it.

### ISSUE THREAD

**Issue by boxed** [crsmithdev/arrow#291]
Got a tip today about arrow and saw that ISO8601 is mentioned a few times in the readme. Tried two things: `arrow.get('2001-01-01')`. That gave me a datetime, but it's a date. 

Then I tried `arrow.get('2001W02')` and it gave me `<Arrow [2001-02-01T00:00:00+00:00]>`. This is wrong because "W02" means week two and not february. Pretty scary that it just silently mis-parses dates like this.

Then I tried times. `arrow.get('00:00')` which just raises a ParseError. Seems a bit weak, but at least it doesn't say 0000-01-01 :P

I have a pretty comprehensive test suite for ISO8601 on my own little project: https://github.com/boxed/iso8601/blob/master/iso8601.py (scroll to the bottom) if you want to fix this. I probably wouldn't recommend using the parsing I do in my lib though, it's super super hacky :P

**Comment by boxed** [comment]
Why was this issue closed? All the issues raised above are still true and your parser is still broken.

**Comment by ramonsaraiva** [comment]
@boxed docs were updated on https://github.com/crsmithdev/arrow/pull/308 according to what you've suggested on the issue title, could you please re-create an issue with a more reasonable acceptance criteria?

**Comment by boxed** [comment]
Ah ok, I'll just create a new ticket with the bad parsing behavior then.

**Comment by ramonsaraiva** [comment]
thank you!
