### ISSUE TITLE
JSON serialization of datetime objects?

### ISSUE THREAD

**Issue by sampeka** [crsmithdev/arrow#300]
It's such a pain that the JSON specification doesn't define how to serialize datetime objects. Would be nice if this library provided a utility to do it, so that serialization is at least consistent across projects that are using this library. Thoughts?

**Comment by systemcatch** [comment]
Actually looking at this further I think the for_json method can provide what you want?

```shell
>>> d = arrow.utcnow()
>>> d
<Arrow [2019-01-16T00:44:15.403152+00:00]>
>>> d.for_json()
'2019-01-16T00:44:15.403152+00:00'
```
