### ISSUE TITLE
Option for duration-focused, human-readable output

### ISSUE THREAD

**Issue by chimaerase** [crsmithdev/arrow#316]
The current output from `humanize()` is specifically focused on duration relative to some fixed reference point in time , e.g. outputs `"in 1 month"` or `"5 days ago"` implicitly reference the present.  This covers a lot of use cases, but can be confusing in situations where the human's focus should be on the duration itself rather than on its relationship to a fixed reference time.

For example, it could be very useful in some cases to output the rough duration of a task, let's say in a user interface or email for system administrator use. In such cases, a human-readable summary of runtime can be useful in making judgement calls about what bottlenecks should be addressed because of the human perception of their impact.  For instance, while imprecise (and probably imperfect), the following output should be a lot clearer to a human administrator with durations presented similarly to:

```
Total run time: 4 minutes 55.87 s
  Subtask A: 10 ms
  Subtask B: 59.90 s
  Subtask C: 3 minutes 41.32 s
  Subtask D: 9.64 s
  Otherwise unaccounted for: 5.00 s
```

This output was generated by a naiive implementation with a similar goal to `humanize`, but that generates durations without a fixed reference time, and also with a variable level of precision in the output.  Clearly I have a specific use case in mind, but I think this type of functionality could be useful to many others as well.

To be more consistent, (and therefore more helpful) than my naiive implementation, a more useful one might allow for a minimum and maximum level of precision in its output.  For example, a client of this feature could optionally specify a minimum and maximum level of granularity to use, e.g. "don't include anything smaller than decimal seconds", or "always show at least millisecond level precision, unless a given quantity has no millisecond component", or "only show precision of one time unit smaller than the largest present in the output". I haven't thought through how to go about implementing all of those ideas, or even whether they're entirely consistent with each other, since others will probably have better ideas for how to go about this. However, all of those use cases seem realistic to me.

A clear question that duration-focused output raises is whether or not to take time zone / daylight savings / calendar into account. I can see arguments on both sides of that, so maybe it would be good to include as an option?

**Comment by andrewelkins** [comment]
The PR #388 should address your issue

**Comment by chimaerase** [comment]
That's great, thank you!
