### ISSUE TITLE
time.sleep(sec) function

### ISSUE THREAD

**Issue by nwgat** [crsmithdev/arrow#317]
would have been sweet if there was a sleep function

**Comment by pypingou** [comment]
How would it be different from the one in the ``time`` module?

**Comment by ownaginatious** [comment]
Maybe @nwgat means a function that blocks until the specified date.

```python
import arrow
a_month_from_now = arrow.now().replace(months=1)
arrow.wait_until(a_month_from_now)
```
`arrow.wait_until` would return immediately if the time has already passed.

That would be kind of cool if you want to build something with cron-like functionality. Perhaps a little out of scope of the project though.

**Comment by nwgat** [comment]
@ownaginatious yes if arrow is to replace time, then it needs a function like this

**Comment by andrewelkins** [comment]
This seems like an edge case as you could do it by comparing the dates. Admittedly not quite as syntactically nice.
