### ISSUE TITLE
Time out of sync on Windows

### ISSUE THREAD

**Issue by Fedjmike** [crsmithdev/arrow#323]
At around 21:45 in UTC+1 I did this:

```
>>> time.ctime(time.time())
'Sun Apr 17 21:46:44 2016'
```

Correct

```
>>> arrow.now()
<Arrow [2016-04-17T20:45:24.272648+01:00]>
>>> arrow.now().to("UTC")
<Arrow [2016-04-17T19:45:26.840795+00:00]>
```

Incorrect, an hour behind

I'm on Windows 7 running Python 3.4.2.

**Comment by jaapz** [comment]
Are you sure the computer's time is set correctly

**Comment by Fedjmike** [comment]
It does appear to be.

**Comment by andrewelkins** [comment]
Covered by https://github.com/crsmithdev/arrow/issues/374
