### ISSUE TITLE
Parsing a complete datetime returns an error. Dateutil does not.

### ISSUE THREAD

**Issue by Guts** [crsmithdev/arrow#324]
``` python
import arrow

test = "2016-04-15T18:21:08.7454873+00:00"
date = arrow.get(test)
date
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\arrow\arrow.py", line 286, in __r
    return '<{0} [{1}]>'.format(self.__class__.__name__, self.__str__()
  File "C:\Python27\lib\site-packages\arrow\arrow.py", line 289, in __s
    return self._datetime.isoformat()
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
```

Using dateutil it seems to be ok:

``` python
from dateutil.parser import parse as dtparse

test = "2016-04-15T18:21:08.7454873+00:00"
date = dtparse(test).strftime("%a %d %B %Y (%Hh%M)")
date
>>> 'Fri 15 April 2016 (18h21)'
```

Windows 10, Python 2.7.11

**Comment by pganssle** [comment]
Are you sure dateutil is getting it right? Doesn't seem like you are actually calling `utcoffset()` in the second code. Try calling `utcoffset()` on the second bit of code to be sure.

**Comment by ztane** [comment]
This is because your fraction has 7 digits, and arrow is horribly b0rken for over 6 digits in the fraction:

     >>> arrow.get('2016-01-01T01:02:03.0000044+01:00')
     <Arrow [2016-01-01T01:02:03+00:44]>

Notice how the last digits of the fraction were pushed into the timezone offset itself

**Comment by ztane** [comment]
Dateutil parses the timestamp as

    >>> dateutil.parser.parse('2016-01-01T01:02:03.0000044+01:00')
    datetime.datetime(2016, 1, 1, 1, 2, 3, 4, tzinfo=tzoffset(None, 3600))

e.g. the fraction was truncated/rounded down, and offset is correct

**Comment by systemcatch** [comment]
Running @ztane  example I get this now.
```shell
>>> arrow.get('2016-01-01T01:02:03.0000044+01:00')
<Arrow [2016-01-01T01:02:03.000004+01:00]>
```

and for @Guts example.
```shell
>>> test = "2016-04-15T18:21:08.7454873+00:00"
>>> date=arrow.get(test)
>>> date
<Arrow [2016-04-15T18:21:08.745487+00:00]>
```

Same for both python 2.7 and 3.6.
