### ISSUE TITLE
Arrow cannot parse long timestamps over a certain size

### ISSUE THREAD

**Issue by rmehlinger** [crsmithdev/arrow#329]
Python has two integer types, it turns out: `int` and `long`. Python integers transition seamlessly between them; on my system; the cutover is at `2**31`; though you can wind up with longs smaller than this value, any integer value greater than 2**31 - 1 will be a `long`.

Unfortunately, arrow cannot parse timestamps of type `long`. Attempting to do so yields the following error:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-36-9408b39836ce>", line 1, in <module>
    arrow.get(2**35)
  File "C:\Python27\lib\site-packages\arrow\api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "C:\Python27\lib\site-packages\arrow\factory.py", line 146, in get
    raise TypeError('Can\'t parse single argument type of \'{0}\''.format(type(arg)))
TypeError: Can't parse single argument type of '<type 'long'>'
```

Interestingly, this doesn't happen with all `long`s, only those strictly greater than `32535291599`, or 3001-01-01T20:59:59+00:00 (again, this may be system dependent). Arrow can parse date strings from beyond this point in time, but not timestamps.

It seems to me that Arrow should be able to parse timestamps of arbitrary size. If there must be a maximum size, it should return an error message indicating that the timestamp is too big.

**Comment by samuelololol** [comment]
any update for this issue ?

**Comment by systemcatch** [comment]
@rmehlinger @samuelololol looks to be working now.
```python
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.get(2**35)
<Arrow [3058-10-26T03:46:08+00:00]>

Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.get(2**35)
<Arrow [3058-10-26T03:46:08+00:00]>
```
