### ISSUE TITLE
replace(day_of_week=...)

### ISSUE THREAD

**Issue by CedrikWinter** [crsmithdev/arrow#336]
Couls the replace method implement the day_of_week feature ?
Next monday would be :
`import arrow
arw = arrow.now()
next_monday = arw.replace(day_of_weeks=1)`
Regards

**Comment by BonkaBonka** [comment]
I put together shift(weekday=...) handling in PR #389.  Does that look like it'll work for you?

**Comment by andrewelkins** [comment]
I'll review it sometime this week.

**Comment by andrewelkins** [comment]
Fixed with #389
