### ISSUE TITLE
Update package on pip

### ISSUE THREAD

**Issue by KartikTalwar** [crsmithdev/arrow#337]
Would it be possible for you to update the package on pypi. There have been many changes here on github (notably https://github.com/crsmithdev/arrow/pull/321) that have not yet been made available via pip.

Thanks!

**Comment by andrewelkins** [comment]
Yeah, let me get chris to do that.

**Comment by KartikTalwar** [comment]
thanks!
ᐧ

**Comment by kdeldycke** [comment]
Looks like the `0.8.0` tag hasn't been pushed to GitHub: https://github.com/crsmithdev/arrow/tree/0.8.0
