### ISSUE TITLE
Unnecessary operation in `__eq__`

### ISSUE THREAD

**Issue by Syeberman** [crsmithdev/arrow#339]
Was reviewing parts of the code and found a bug in `__eq__`: `self._get_datetime` is called twice on `other`.  Clearly line 721 should be deleted.

https://github.com/crsmithdev/arrow/blob/master/arrow/arrow.py#L716

```
    def __eq__(self, other):

        if not isinstance(other, (Arrow, datetime)):
            return False

        other = self._get_datetime(other)

        return self._datetime == self._get_datetime(other)
```

**Comment by andrewelkins** [comment]
Yep, cleaned up.
