### ISSUE TITLE
There is no 0.8.0 version description in History.md

### ISSUE THREAD

**Issue by svetlyak40wt** [crsmithdev/arrow#340]
Hi!

Version have changed: https://github.com/crsmithdev/arrow/blob/master/arrow/__init__.py#L7
But changelog wasn't updated :(

What is new in 0.8.0?

**Comment by kdeldycke** [comment]
`0.8.0` tag hasn't been pushed either. See: https://github.com/crsmithdev/arrow/issues/337#issuecomment-226171198

**Comment by andrewelkins** [comment]
I'll fix that today

**Comment by underyx** [comment]
@andrewelkins friendly reminder about this issue

**Comment by miso-belica** [comment]
But 0.8.0 is already available on PyPI. :O

**Comment by patricksnape** [comment]
The 0.8.0 tag still hasn't been created @andrewelkins

**Comment by gandaro** [comment]
Have any incompatible changes to the API been made from version 0.7.0 to 0.8.0?

**Comment by andrewelkins** [comment]
tag created, history updated for 0.9.0 and 0.10.0, read docs updated as well.

@gandaro not that I'm aware of
