### ISSUE TITLE
Support .days / .months / .years of dateutil.relativedelta's relativedelta

### ISSUE THREAD

**Issue by Lvl4Sword** [crsmithdev/arrow#346]
Having the option to support .days / .months / .years from relativedelta would give arrow far more use cases.
It's a little strange that relativedelta is referenced in the "Too many types: date, time, datetime, tzinfo, timedelta, relativedelta, etc." of the "Why?" up at the top of https://arrow.readthedocs.io/en/latest/ but isn't supported. :-(

**Comment by systemcatch** [comment]
Sorry this issue was ignored so long, I'm just making a quick pass over here.

I know that arrow uses relativedelta internally quite a bit, especially in the shift method.

**Comment by Lvl4Sword** [comment]
Completely forgot I had posted this.
Is this something that's been made possible?
If not, are there any plans for this?

**Comment by systemcatch** [comment]
I'm not entirely sure this is what you want but take a look at https://github.com/crsmithdev/arrow/blob/master/arrow/arrow.py#L513

```shell
>>> dt=arrow.now()
>>> dt
<Arrow [2019-01-17T11:37:02.256978+00:00]>
>>> dt.shift(weeks=-3)
<Arrow [2018-12-27T11:37:02.256978+00:00]>
>>> dt.replace(day=5)
<Arrow [2019-01-05T11:37:02.256978+00:00]>
```

**Comment by systemcatch** [comment]
I'm closing this for now, feel free to reopen if your use case still isn't met.
