### ISSUE TITLE
Can arrow be used to validate if a string is ISO 8601 formed?

### ISSUE THREAD

**Issue by blurrcat** [crsmithdev/arrow#348]
I'm using arrow in my validation logic, something like

``` py
try:
    return arrow.get(value)
except arrow.parser.ParseError as e:
    raise ValidationError(message=str(e))
```

However, arrow can be very loose on parsing things:

```
In [2]: arrow.get('http://127.0.0.1:5000')
Out[2]: <Arrow [5000-01-01T00:00:00+00:00]>
```

Is there any recommended way to validate if a string is ISO 8601 formed? Is arrow suitable for this use case?

**Comment by bsolomon1124** [comment]
@blurrcat I stumbled upon your question here and wanted to point out that `dateutil` as of a new version (2.7-something, I think) has ISO-specific support:

```python
from dateutil.parser import isoparse

isoparse('http://127.0.0.1:5000')  # raises
isoparse(time.asctime())
isoparse('2019-03-04T00:00:00Z')  # ok
```

**Comment by systemcatch** [comment]
Interesting maybe we could backport isoparse into arrow since the dateutil requirement is set to 2.6.0

**Comment by blurrcat** [comment]
Looking back now I think the point I missed is that Arrow is not intended to be used as a validator. The ability to parse somewhat valid strings is just a convenience.
