### ISSUE TITLE
Allow escaping of characters in format()

### ISSUE THREAD

**Issue by cynddl** [crsmithdev/arrow#35]
In French, hours are formatted like "8 h 40" and not "8:40". But in an arrow's format string, _h_ display directly the hours. Is it possible to add a key like _!_ to force _h_ to be displayed normally ("hh !h mm")?

**Comment by oryband** [comment]
:+1:

**Comment by sametmax** [comment]
Got the same problem today, and had to to d.datetime.strftime. Which sucked cause it doesn't handle unicode properly in 2.7. BTW, why do we have different operators to format with arrow and datetime ? It should be the same. %stuff works well, and identify easily what's marker and what's not.

**Comment by allanlewis** [comment]
Same issue here - I'd like to format as "[date] at [time]", e.g. "Fri 01 May 2015 at 16:32", but the 'a' gets translated into AM/PM.

**Comment by sukrit007** [comment]
:+1: for square bracket support.

**Comment by andrewelkins** [comment]
I like the bracket approach. I don't have time at the moment to make the PR for it though, does anyone else. I'd happily review and merge a PR with this.

**Comment by leonciokof** [comment]
:+1:

**Comment by ComFreek** [comment]
:+1:

**Comment by AndydeCleyre** [comment]
I wouldn't mind throwing a `\` before each escaped character, but I would love to have this feature in whatever form.

**Comment by AlJohri** [comment]
👍 this would be amazing

**Comment by silverp1** [comment]
:+1:

**Comment by aGHz** [comment]
👍

**Comment by andrewelkins** [comment]
Time to tackle this one :+1:

**Comment by karbassi** [comment]
Seems like #290 fixed this but I can't seem to be able to make it work.

**Comment by systemcatch** [comment]
This now basically works.
```python
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> date_format = "YYYY-MM-DD h [h] m"
>>> my_date = "2018-03-09 8 h 40"
>>> arrow.get(my_date, date_format)
<Arrow [2018-03-09T08:40:00+00:00]>
```
But it's not documented anywhere on https://arrow.readthedocs.io/en/latest/ so that needs to be fixed.
