### ISSUE TITLE
day vs days, month vs months

### ISSUE THREAD

**Issue by miracle2k** [crsmithdev/arrow#350]
`arrow.Arrow.range('day', start, end)`

but:

`point.replace(days=1)`

If I have a function that does some date math and I want to support multiple granularities, I find myself writing a function like this:

```
def replace_by_granularity(point, granularity, count):
    argname = {
        'week': 'weeks',
        'quarter': 'quarters',
        'year': 'years',
        'month': 'months',
        'day': 'days'
    }[granularity]
    return point.replace(**{argname: count})
```

So that my user can give me "day", and I can use it as both "day" and "days".

It's simple enough to do, but I wonder if there are other options that I am missing, or whether we might come up with an API that allows time shifting using the singlular-version of the keywords.

**Comment by systemcatch** [comment]
Does the shift function solve your problem? The old replace syntax doesn't work anymore.

```python
>>> arw=arrow.utcnow()
>>> arw
<Arrow [2019-01-24T17:34:51.085319+00:00]>
>>> arw.shift(weeks=+3)
<Arrow [2019-02-14T17:34:51.085319+00:00]>
```
