### ISSUE TITLE
does it handle BC dates?

### ISSUE THREAD

**Issue by BoYanSTKO** [crsmithdev/arrow#352]
I have a date ''-299-01-01T00:00:00Z'' which could be translated to 300BC. But Arrow gives me the error:  ParserError: `Could not match input to any of [u'YYYY-MM-DDTHH:mm:ss'] on '-299-01-01T00:00:00Z'`

**Comment by jaapz** [comment]
Arrow just wraps the `datetime` package (among others) from the python standard library, and as far as I know `datetime` does not handle dates before 1AD.

**Comment by andrewelkins** [comment]
Confirmed. It won't work with that date.
