### ISSUE TITLE
Parse timestamp with milliseconds/microseconds

### ISSUE THREAD

**Issue by henridwyer** [crsmithdev/arrow#357]
Arrow version 0.8.0
arrow.get cannot handle large timestamps because datetime throws a ValueError when a timestamp results in a year greater than or equal to 10000.

``` python

>>> import arrow
>>> arrow.get(1000000000000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/arrow/factory.py", line 144, in get
    return self.type.utcfromtimestamp(arg)
  File "/usr/local/lib/python2.7/site-packages/arrow/arrow.py", line 114, in utcfromtimestamp
    dt = datetime.utcfromtimestamp(timestamp)
ValueError: year is out of range
```

However,  most of the time, that error stems from the fact that the timestamp is not in seconds but in ms or ns.

I'm suggesting that if the timestamp is too large for datetime to parse properly, that means it's not in seconds and we should divide it appropriately.

What do you think?

**Comment by andrewelkins** [comment]
An interesting thought, but I don't like that hidden logic.

**Comment by henridwyer** [comment]
I don't see this as hidden logic, but rather correctly interpreting the input. In fact I see it much like when the input is a string, arrow does it's best to figure out what it is and doesn't require perfectly formatted input (one of arrow's main points is it's smart 'get' function).
In this case if the input treated as seconds would correspond to a year > 10000, then that is the wrong interpretation (python datetime objects are not meant to be used for that). Therefore, the parsing is wrong.

**Comment by andrewelkins** [comment]
I'm coming around to this idea. Care to submit a PR?

**Comment by henridwyer** [comment]
@andrewelkins I opened a PR for this when I created the issue: https://github.com/crsmithdev/arrow/pull/358/

**Comment by flxfxp** [comment]
Any news on this? Thanks!

**Comment by uburuntu** [comment]
Up 😏

**Comment by jadchaar** [comment]
As discussed in #615, think that it may be better to keep such functionality to a new parsing token like `x`. @systemcatch and I think that doing this automatically is masking too much logic and may be better kept for another parsing token. If a user wants to do this, he or she can use a token. If someone would like to open a PR to add this token, please do :).
