### ISSUE TITLE
range and span_range with interval size

### ISSUE THREAD

**Issue by richard-engineering** [crsmithdev/arrow#362]
It would be good to have a parameter for interval size for arrow.Arrow.range and arrow.Arrow.span_range.

Eg I want a range across 5 days between some start and end date, or 2 weeks, etc.

**Comment by andrewelkins** [comment]
Can you give us a code example?

**Comment by rhan-mentad** [comment]
Here's an example of how I ended up implementing the code (with 'day' being hardcoded in this example but the ideal implementation wouldn't be limited to day. Uses funcy.
```
    from funcy import flatten, chunks
    import arrow

    def _split_time_range(start_time, end_time, **kwargs):
        time_range = arrow.Arrow.range('day', arrow.get(start_time), arrow.get(end_time))
        start_times = flatten(chunks(1, kwargs.get('chunk_size', 7), time_range))
        start_end_times = {
            c_start_time: start_times[index + 1]
            if index + 1 < len(start_times) else end_time
            for index, c_start_time in enumerate(start_times)
        }
        return start_end_times
```

**Comment by andrewelkins** [comment]
Got it appreciate the example. I wonder if it would be more expressive to use a new method called "interval" for this purpose.

**Comment by rhan-mentad** [comment]
Having a new method called interval sounds fine. Could probably use arrow.range and arrow.span_range underneath like the example.

**Comment by andrewelkins** [comment]
Exactly. No need to duplicate code.

**Comment by systemcatch** [comment]
Done in #386 so closing.

**Comment by dongli** [comment]
It seems `interval` corresponds to `span_range`. What about `range`, when I just need one single value of time, not a tuple?

**Comment by systemcatch** [comment]
@dongli something like this?

```shell
(arrow) chris@ThinkPad:~/arrow$ python
Python 3.7.4 (default, Sep 19 2019, 11:01:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> right_now=arrow.utcnow()
>>> five_hours_ago=right_now.shift(hours=-5)
>>> right_now
<Arrow [2020-03-06T20:12:27.474979+00:00]>
>>> five_hours_ago
<Arrow [2020-03-06T15:12:27.474979+00:00]>
>>> list(arrow.Arrow.range("minute", five_hours_ago, right_now, limit=1))
[<Arrow [2020-03-06T15:12:27.474979+00:00]>]
```
