### ISSUE TITLE
pypi version at 0.8.0, github latest release is 0.6.0 official 0.7.0 highest

### ISSUE THREAD

**Issue by baldwindc** [crsmithdev/arrow#363]
The latest version of arrow listed in pypi is 0.8.0 (https://pypi.python.org/pypi/arrow/0.8.0). 

The latest version of arrow listed on Github is 0.7.0. 

Is there a mismatch somewhere?

**Comment by andrewelkins** [comment]
Fixed. Push latest to pypi and update github versions
