### ISSUE TITLE
arrow.now() in BST seems to be reported incorrectly

### ISSUE THREAD

**Issue by BackwardSpy** [crsmithdev/arrow#367]
It's possible that I'm just misunderstanding how this is supposed to work, but at the moment many of our logs are showing the time as one hour behind the real local time. I was under the impression that `arrow.now()` should return the correct local time, however for me it is showing the time as one hour behind what is reported by the unix `date` utility.

Below is some python repl output in which I get the 'now' for GMT, Europe/London, UTC, BST, and finally US/Pacific. In the first four cases, it shows the same time with a +0 or a +1 on the end. In the last case, it shows the (presumably) correct US/Pacific time, with the -7 on the end.

```
>>> arrow.now()
<Arrow [2016-10-21T08:15:48.253220+01:00]>
>>> arrow.now('GMT')
<Arrow [2016-10-21T08:15:59.854732+00:00]>
>>> arrow.now('Europe/London')
<Arrow [2016-10-21T08:16:04.733783+01:00]>
>>> arrow.now('UTC')
<Arrow [2016-10-21T08:16:11.021377+00:00]>
>>> arrow.now('BST')
<Arrow [2016-10-21T08:16:13.724043+01:00]>
>>> arrow.now('US/Pacific')
<Arrow [2016-10-21T01:16:35.515685-07:00]>
```

My question is this; why do `arrow.now()` and `arrow.now('Europe/London')` show 8:15 instead of 9:15?

Thanks.

**Comment by andrewelkins** [comment]
We do have tests for that. https://github.com/crsmithdev/arrow/blob/master/tests/arrow_tests.py#L36

What happens if you output 
`datetime.utcnow().replace(tzinfo=tz.tzutc())`

**Comment by BackwardSpy** [comment]
(note: I set my system time back to October 21st to simulate still being under BST)

```
In [20]: arrow.now()
Out[20]: <Arrow [2016-10-21T09:38:18.346337+01:00]>

In [21]: arrow.now('GMT')
Out[21]: <Arrow [2016-10-21T08:38:21.635101+00:00]>

In [22]: arrow.now('Europe/London')
Out[22]: <Arrow [2016-10-21T09:38:25.907187+01:00]>

In [23]: arrow.now('UTC')
Out[23]: <Arrow [2016-10-21T08:38:42.506671+00:00]>

In [24]: arrow.now('BST')
Out[24]: <Arrow [2016-10-21T09:38:45.115069+01:00]>

In [25]: arrow.now('US/Pacific')
Out[25]: <Arrow [2016-10-21T01:38:51.187329-07:00]>

In [26]: datetime.utcnow().replace(tzinfo=tz.tzutc())
Out[26]: datetime.datetime(2016, 10, 21, 8, 38, 56, 75207, tzinfo=tzutc())
```

This time around, the dates and times given by both `arrow` and `datetime` look correct.
I don't remember updating arrow since I posted this issue, but it is possible I did so and just forgot about it. Unless you can think of a way to better simulate whatever was happening when I first posted the issue, then I think it'd be best to just call this a non-issue for now. If it starts happening again next year, I'll be sure to post back. :)

Thanks for your help.

**Comment by andrewelkins** [comment]
Thanks for the reply!
