### ISSUE TITLE
+ or - prefix with UTC 00:00

### ISSUE THREAD

**Issue by 1CM69** [crsmithdev/arrow#369]
First off, fantastic library for Python, thanks!

While testing I noticed that using:
`utc = arrow.utcnow()`
gives the result:
`<Arrow [2016-11-10T13:51:58.970460+00:00]>`
and noticed that the UTC offset zero and is displayed as positive.
This is perfect for me living in the UK, currently on GMT at the time of writing and this is how I have regularly seen the offset displayed.
+00:00 when on GMT
+01:00 when on BST

Now in my python application I need a shortened version of the TIME variable so I made use of the format() function in arrow as:
`arrow.utcnow().format('HH:mmZZ')`
but noticed that this displays the output as:
`13:51-00:00`

Suddenly the positive offset is shown as negative.

Not a biggy, just for consistency I needed it as positive.

Anyway, for the moment I edited the line in formatter.py file from:
`sign = '+' if total_minutes > 0 else '-'`
to
`sign = '+' if total_minutes >= 0 else '-'`

for me now, this fits in with the rest of my application.

Regards..,

**Comment by mrmrwat** [comment]
I agree. This surprised me recently, so I've created a PR for it here: https://github.com/crsmithdev/arrow/pull/377

**Comment by bukzor** [comment]
This has been merged.

**Comment by mrmrwat** [comment]
Good stuff. Thanks!

**Comment by andrewelkins** [comment]
Merged and pushed to pypi
