### ISSUE TITLE
update pypi and rtfd

### ISSUE THREAD

**Issue by bukzor** [crsmithdev/arrow#381]
These are behind the current state of github (0.10.0):

  * https://pypi.python.org/pypi/arrow  (0.9.0)
  * http://arrow.rtfd.io/en/latest/   (0.4.4)

**Comment by andrewelkins** [comment]
Yep, Chris will update them shortly.

**Comment by bukzor** [comment]
Looks all up to date, thanks!
The docs still say 0.4.4 at the bottom, but I see the recent changes.

**Comment by andrewelkins** [comment]
Yeah, not sure why that is. May take a look tomorrow.
