### ISSUE TITLE
Version 0.9.0 and 0.10.0 arrow.get breaks on too much microsecond precision.

### ISSUE THREAD

**Issue by caseymacphee** [crsmithdev/arrow#392]
A particular timestamp that we got recently from an upstream system wasn't digestable by arrow.get()
2016-12-13T18:32:12.9999999999Z
'microsecond must be in 0..999999'
but works on 0.8.0. May be the appropriate behavior if more precision isn't legal, but wanted to bring it to attention anyway because arrow.get has previously handled it just fine.

https://github.com/crsmithdev/arrow/issues/341

**Comment by andrewelkins** [comment]
Confirmed. Thanks for bringing it up. We'll handle it in #341
