### ISSUE TITLE
Couple questions about `GermanLocale` / `AustriaLocale`

### ISSUE THREAD

**Issue by brutus** [crsmithdev/arrow#394]
`GermanLocale` and `AustriaLocale` use the same mixin: `_DeutschLocaleCommonMixin`:

```py
class GermanLocale(_DeutschLocaleCommonMixin, Locale):

    names = ['de', 'de_de']

    timeframes = _DeutschLocaleCommonMixin.timeframes.copy()
    timeframes['days'] = '{0} Tagen'
```
```py
class AustriaLocale(_DeutschLocaleCommonMixin, Locale):

    names = ['de', 'de_at']

    timeframes = _DeutschLocaleCommonMixin.timeframes.copy()
    timeframes['days'] = '{0} Tage'
```

This is a good idea but here are some questions:

1. Is the correct form of `timeframes['days']` for Austria really _"Tage"_?

    So e.g. _"vor 3 Tage"_? Instead of _"vor 3 Tagen"_? Sounds weird for a German speaker (no offense, just wondering).

2. Should `AustriaLocale` be the default for `de` over `GermanLocale`?

    I don't mean to judge or anything, but because of the way the local names are handled in `_map_locales`, the `AustriaLocale` will be set for `de` not `GermanLocale` (because it comes later and overwrites the `de` key… if I interpret the code correctly):

    ```py
    def _map_locales():

        locales = {}

        for cls_name, cls in inspect.getmembers(sys.modules[__name__], inspect.isclass):
            if issubclass(cls, Locale):
                for name in cls.names:
                    locales[name.lower()] = cls

        return locales
    ```

My problem is that in my environments the `AustriaLocale` is picked over the `GermanLocale` every time, so I ended up with the wrong format for  `timeframes['days']`.

**Comment by brutus** [comment]
Might https://github.com/crsmithdev/arrow/pull/395 be a solution?

Considering that the Austrian version _"vor 3 Tage"_ is correct.

**Comment by andrewelkins** [comment]
Can you double check now that 395 was merged?

**Comment by brutus** [comment]
Sorry for the late response, will do. Traveling right now, will have a look not later than next monday.

**Comment by brutus** [comment]
As a follow up: according to this [German SE answer](http://german.stackexchange.com/a/34107/25165) (german language only) the special case for `timeframes['days']` in `AustriaLocale` is wrong as expected.

I created another pull request, which removes it: https://github.com/crsmithdev/arrow/pull/408

PS: all done from the browser, so no manual running testing or anything. The build passes though.

**Comment by brutus** [comment]
Looks fine, all my test pass :)
