### ISSUE TITLE
Add Day of Year Support

### ISSUE THREAD

**Issue by ZachDischner** [crsmithdev/arrow#396]
It would be excellent to be able to include 3 digit day-of-year support for date formats. 

For example, using `datetime`

```
In [14]: datetime.datetime.strptime("2016-360","%Y-%j")
Out[14]: datetime.datetime(2016, 12, 25, 0, 0)
```

The equivalent with `arrow` could be

```
arrow.get("2016-360")
```

For background, most of the datetimes I work with for spacecraft telemetry timestamping utilizes the day-of-year format since it is is pretty locale agnostic (2016/12/11 vs 2016/11/12).

**Comment by Zamubafoo** [comment]
While an implementation of the 'j' token would be a nice feature, you can easily extract the date into arrow without much trouble:

`dayOfYear=arrow.Arrow.strptime("2016-360","%Y-%j") `

This gets you to the correct time inside an Arrow object which is easy to work with, then you can export it via:

`dayOfYear.strftime("%Y-%j")`

It's nothing amazing, but it definitely beats datetime and the bunch.
