### ISSUE TITLE
arrow.strftime('%s') broken

### ISSUE THREAD

**Issue by wphilips** [crsmithdev/arrow#400]
According to the linux man pages,  strftime("%s") 
should return "The  number  of  seconds  since  the  Epoch,  1970-01-01  00:00:00  +0000  (UTC)."

However it does not. The strftime call below should return 0, not -3600
My timezone is CET. If I run the code below after setting the environment variable
TZ=UTC, the code returns the correct value 0, but it should always return 0, 
irrespective of the timezone

date
Tue Dec 27 20:34:25 CET 2016
sudo pip install --upgrade arrow
ipython -i
import arrow
a=arrow.get('1970-01-01 00:00:00')
print a
1970-01-01T00:00:00+00:00
print a.strftime('%s')
-3600
print a.tzinfo
tzutc()

**Comment by Zamubafoo** [comment]
It's a datetime issue, not arrow. Run the following datetime call and you will get the same result.

`datetime.datetime(1970,1,1,0,0,0,0,None).strftime('%s')`

As for Arrow, it actually has a call exactly for getting the timestamp, 

```
arrow.utcnow().timestamp       # standard i.e. 1482975679

arrow.utcnow().float_timestamp # microseconds i.e. 1482975688.754092
```

**Comment by wphilips** [comment]
You are right. Even the following gets the wrong answer:
 datetime.datetime(1970,1,1,0,0,0,0, tz.tzutc()).strftime('%s')
Out[23]: '-3600'

I suppose your answer implies that arrow uses datetime internally?
In any case the result is that arrow fails to properly parse dates.

**Comment by Zamubafoo** [comment]
Arrow does properly parse dates, even the Unix Epoch. This issue lies with using 

`arrow.get('1970-01-01T00:00:00+00:00').strftime('%s')` 

to get the timestamp instead of using arrow's appropriate API call to get the timestamp, 

`arrow.get('1970-01-01T00:00:00+00:00').timestamp`

Looking further into it, it seems to originate from the python `time` module which defaults to using local time instead of using UTC when handling `time.strftime` calls which carries over from the base C libs. It's more user error of not adding TZ data.

**Comment by wphilips** [comment]
Ok, that explains it.  For future reference.:

1. For the above example,  arrow.get('1970-01-01T00:00:00+00:00').strftime('%s'),
glibc's strftimne is called with the following input:
{tm_sec = 0, tm_min = 0, tm_hour = 0, tm_mday = 1, tm_mon = 0, 
  tm_year = 70, tm_wday = 4, tm_yday = 0, tm_isdst = 0, tm_gmtoff = 0, 
  tm_zone = 0x0}

and returns "-3600"

2. Even worse: arrow.get('1970-01-01T00:00:00+09:00').strftime('%s') and
arrow.get('1970-01-01T00:00:00').replace(tzinfo=tz.gettz('US/Pacific')).strftime('%s')
also return -3600, i.e., the time offset is ignored 
3. See also 
https://sourceware.org/bugzilla/show_bug.cgi?id=17189

That thread ends with the conclusion "This means that strftime() always treats the supplied struct tm as if it were in the local time zone;" which explains this behaviour. However, it also states that 
this behaviour is documented in the (glibc) strftime man-page. Currently (fedora 24 man page), this is no longer the case.







with localtime,

**Comment by andrewelkins** [comment]
@wphilips and @Zamubafoo You folks are amazing. Thanks for hashing the issue out and coming to a resolution. Perhaps I need to start a "Tips and Tricks" section of the docs page.
