### ISSUE TITLE
? arrow to epoch with fractional value

### ISSUE THREAD

**Issue by apiszcz** [crsmithdev/arrow#412]
Is there a method to retain the fractional seconds in the following example? Thanks.

(Pdb) ado=arrow.get('2013-05-07T04:24:24.152325')
(Pdb) ado.timestamp
1367900664

**Comment by systemcatch** [comment]
```shell
>>> ado=arrow.get('2013-05-07T04:24:24.152325')
>>> ado.float_timestamp
1367900664.152325
```
