### ISSUE TITLE
.humanize for near-zero duration says "just now"

### ISSUE THREAD

**Issue by bukzor** [crsmithdev/arrow#416]
This is very confusing for a field that is meant to be duration.
Consider, I may have a very short duration event that occurred weeks ago.

Arrow will say this event was "just now".
A more accurate description would be "instantly".

**Comment by bjmc** [comment]
My understanding of "humanize()" is that it isn't offering a duration, but rather a human-language version of a "time delta" between two points in time, so we have: "a few minutes ago", "a week ago", "a year ago", etc.

**Comment by bukzor** [comment]
It does both depending on the arguments.

**Comment by sumeet** [comment]
ya, the `only_distance` param.

here's a repro:

```python
In [1]: import arrow

In [2]: now = arrow.now()

# we're going to compare everything against `t`, which is the relative time in the past we want to compare against

In [3]: t = arrow.now() - timedelta(days=100)

# when the result is minutes ago, the `only_distance` parameter strips off the relativity
# information from the time
In [6]: t1 = t - timedelta(minutes=3)

In [8]: t1.humanize(other=t)
Out[8]: u'3 minutes ago'

In [7]: t1.humanize(other=t, only_distance=True)
Out[7]: u'3 minutes'
```

THIS is what @bukzor is talking about. when the result is only 1 second, the same relative-to-now time string is returned, regardless of the `only_distance` param

```python
In [9]: t2 = t - timedelta(seconds=1)

In [11]: t2.humanize(other=t)
Out[11]: u'just now'

In [12]: t2.humanize(other=t, only_distance=True)
Out[12]: u'just now'
```

**Comment by IgorAntun** [comment]
I have the exact same use case and I'm running into the same issue.. Thanks for the PR @bukzor , let's hope it gets merged eventually (though it's been quite a while since you sent it)
