### ISSUE TITLE
Can a new version of arrow be published to pypi?

### ISSUE THREAD

**Issue by mtrahan** [crsmithdev/arrow#419]
I need the pattern cache changes in the DateFormatParser but those aren't yet published to pypi.

Thanks!

**Comment by andrewelkins** [comment]
Will do that today!

**Comment by mtrahan** [comment]
Great thanks!

**Comment by Syeberman** [comment]
While you're at it, https://arrow.readthedocs.io/en/latest/ should be updated.

**Comment by mtrahan** [comment]
Any update on this? Thanks!

**Comment by bram85** [comment]
For my [topydo](https://github.com/bram85/topydo/) project I'd like to use the coarse human dates (#388), but unfortunately the functionality still hasn't landed in PyPi.

**Comment by chimaerase** [comment]
Looks like the latest code still hasn't landed on PyPi, though it's been quite some time.  Would it be possible to make a new release?  I'm also looking for #388

**Comment by systemcatch** [comment]
0.11.0 and 0.12.0 were released on PyPi in November 2017 so we should be good here.
