### ISSUE TITLE
month=+1 when month=12 does not increment year

### ISSUE THREAD

**Issue by WDBell** [crsmithdev/arrow#420]
First I replace the current date's month with 12. Then I add one to the month. However, the year remains the same. (Have I finally lost my mind?)

```
>>> import arrow
>>> now = arrow.now()
>>> now = now.replace(month=12)
>>> now
<Arrow [2017-12-21T11:28:10.008608-05:00]>
>>> now = now.replace(month=+1)
>>> now
<Arrow [2017-01-21T11:28:10.008608-05:00]>

```

**Comment by jaapz** [comment]
The last call should be `now = now.replace(months=+1)` note the extra `s` in `months` instead of `month`.

**Comment by WDBell** [comment]
Thank you! Why didn't I see that.
