### ISSUE TITLE
h and hh don't seem to work

### ISSUE THREAD

**Issue by nerdbaggy** [crsmithdev/arrow#422]
arrow.get("7", "h")
arrow.get("07", "hh")

throws

arrow.parser.ParserError: Unrecognized token 'h'
arrow.parser.ParserError: Unrecognized token 'hh'

**Comment by jverce** [comment]
@nerdbaggy why was this closed? I'm getting the same error, even though I'm following the docs here:
http://arrow.readthedocs.io/en/latest/#tokens

**Comment by jverce** [comment]
Never mind, it was related to the version (`hh` was not covered in old versions).
