### ISSUE TITLE
Bump to 0.11?

### ISSUE THREAD

**Issue by WyseNynja** [crsmithdev/arrow#423]
I was trying to use the "granularity" kwarg for humanize and was getting an error. For now I'm installing from git, but it would be nice to bump the version here and get a new version on PyPI

**Comment by idxn** [comment]
I would like to follow-up on this topic. Is a release date of 0.11 scheduled yet? I'm looking forward to installing the 0.11 from PyPi instead of building the latest myself.

**Comment by victordomingos** [comment]
I have also hit the "granularity" wall a few hours ago. I am hoping we can soon update arrow with pip to get that option.

**Comment by rhan-mentad** [comment]
Any movement on this?

**Comment by systemcatch** [comment]
Version 0.11.0 (and onwards) are on PyPi now so this can be closed.
