### ISSUE TITLE
Unexpected date parsing

### ISSUE THREAD

**Issue by piskvorky** [crsmithdev/arrow#434]
Weird bugs were tracked to Arrow parsing dates incorrectly (and silently):

```python
import arrow
arrow.__version__
# 0.10.0
arrow.get('2016')
# <Arrow [1970-01-01T00:33:36+00:00]>
```

Is that expected/intended? What is Arrow interpreting the string `2016` as?

Also, this was not what I expected:
```python
arrow.get('05/02/2017', ['YYYY', 'MM/DD/YYYY'])
# <Arrow [2017-01-01T00:00:00+00:00]>
arrow.get('05/02/2017', ['MM/DD/YYYY', 'YYYY'])
# <Arrow [2017-05-02T00:00:00+00:00]>
```

Format order matters, and if order wrong, produce silent errors?

**Comment by pganssle** [comment]
Looks like it's being interpreted as an epoch time. 2016 seconds is a bit over 33 minutes.

**Comment by hosseinmoein** [comment]
I have another example that indicates arrow doing greedy matching and producing wrong results:
```
arrow.get('Jun-2019', ['MMM-YY', 'MMM-YYYY'])
<Arrow [2020-06-01T00:00:00+00:00]>

arrow.get('Jun-2019', ['MMM-YYYY', 'MMM-YY'])
<Arrow [2019-06-01T00:00:00+00:00]>
```
In the first example it matches incorrectly with `MMM-YY`.
But if you put `MMM-YYYY` first, than it matches with the correct pattern
