### ISSUE TITLE
fr_CA locale support?

### ISSUE THREAD

**Issue by bjmc** [crsmithdev/arrow#436]
I'd like to request support for Canadian French as a locale option.

If it's similar enough, perhaps we could just add `'fr_ca'` to the existing French locale? If there are differences, maybe we could follow the model of the German language mixin?

Are there any French Canadians who could offer their expertise?

**Comment by ramonsaraiva** [comment]
hey @bjmc, what are the differences between the languages `french` and `canadian french`? could you specify those so someone could potentially work on it?

**Comment by bjmc** [comment]
Thanks @ramonsaraiva unfortunately, if I knew the differences, I could probably make the changes myself.

I'm hoping some French speakers might be able to chime in.

**Comment by ramonsaraiva** [comment]
got it, i'll leave it opened then

**Comment by remyroy** [comment]
French Canadian here. Formatting date patterns is slightly different in fr_CA compared to fr (fr_FR). You can see it if you compare the date provided by [CLDR](http://cldr.unicode.org/) for instance. There are also a few other minor differences.

See a recent diff [here](https://gist.github.com/remyroy/cc20da064059900eafbeb45367c7a68c).
