### ISSUE TITLE
Weird issue with London timezone

### ISSUE THREAD

**Issue by pedropregueiro** [crsmithdev/arrow#439]
hey, do you have any idea why the below return different things?

```
# using pytz timezone
> arrow.utcnow().to(pytz.timezone('Europe/London'))
< <Arrow [2017-06-09T16:42:36.203567+01:00]>

# using Arrow's default
> arrow.utcnow().to('Europe/London')
< <Arrow [2017-06-09T15:42:36.203567+01:00]>

# UTC
> arrow.utcnow()
< <Arrow [2017-06-09T15:42:36.203567+00:00]>
```

I was fighting a bit with the `Europe/London` timezone until I found this solution, but I would like to understand why is the hour the same for both UTC and Europe/London, even though the timezone offset is clearly there

**Comment by pganssle** [comment]
@pedropregueiro I cannot reproduce this issue with `python-dateutil` version 2.6.0 and `arrow` version 0.10.0. What versions of these two things do you have?

```python
import pytz
import arrow

print(arrow.__version__)       # 0.10.0
print(dateutil.__version__)    # 2.6.0

base = arrow.get(2017, 6, 9, 15, 42, 36)
print(base.to('Europe/London'))                  # 2017-06-09T16:42:36+01:00
print(base.to(pytz.timezone('Europe/London')))   # 2017-06-09T16:42:36+01:00
```

There are also some fixes to the Europe/London time zone specifically in the 2.6.1 version of dateutil, though I am fairly certain they are not relevant here.

**Comment by pedropregueiro** [comment]
I'm using version 2.4.2 of dateutil and this is the output.
```
> print(base.to('Europe/London'))
< 2017-06-09T15:42:36+01:00

> print(base.to(pytz.timezone('Europe/London')))
< 2017-06-09T16:42:36+01:00
```
And I just upgraded to 2.6.0 and it seems to have fixed the issue:
```
> print(base.to('Europe/London'))
< 2017-06-09T16:42:36+01:00

> print(base.to(pytz.timezone('Europe/London')))
< 2017-06-09T16:42:36+01:00
```

thanks for the help @pganssle!
