### ISSUE TITLE
No version 1 release

### ISSUE THREAD

**Issue by jmgurney** [crsmithdev/arrow#443]
If you feel the API is stable, please release a version 1 so that we know that it can be depended upon.  Sem versioning says major version zero allows API to be broken at any time.

Until there is a major version 1 release, I will not use this as a future release may break my software.

**Comment by idxn** [comment]
@crsmithdev I'm not quite sure the status of this library. Is this still be maintained? We have not heard from you for quite a while.

**Comment by drunckoder** [comment]
A very useful stuff here. Too sad to see it's dying :(

**Comment by Ni-Knight** [comment]
Please don't let this library die :(

**Comment by systemcatch** [comment]
I'm hoping to kickstart work on this repo, would be useful to have more people helping out as collaborators though.

Regarding a possible Version 1.0 I can't say when that could happen, lots of work needs to be done.
