### ISSUE TITLE
Day of Week bug

### ISSUE THREAD

**Issue by 4kpt** [crsmithdev/arrow#446]
assert arrow.get("Tuesday", "dddd").format("dddd") == 'Monday'

**Comment by lightlace** [comment]
I built a little program out of this:

```
#!/usr/bin/env/python3

import arrow

def assertion(argument):
    arg = arrow.get(argument,"dddd").format("dddd")
    print (arg)

assertion()
```

When the argument is foo, it throws this error:

```
Traceback (most recent call last):
  File "arrow446.py", line 9, in <module>
    assertion("foo")
  File "arrow446.py", line 6, in assertion
    arg = arrow.get(argument,"dddd").format("dddd")
  File "/usr/lib/python3.6/site-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/arrow/factory.py", line 198, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/usr/lib/python3.6/site-packages/arrow/parser.py", line 159, in parse
    raise ParserError('Failed to match \'{0}\' when parsing \'{1}\''.format(final_fmt_pattern, string))
arrow.parser.ParserError: Failed to match '(?P<dddd>(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday))' when parsing 'foo'
```

So i assume, that it doesn't get the argument "Tuesday" at all and takes {0}, which is in this case "Monday".

Unfortunately i don't have more clues on that..

**Comment by smirnoffs** [comment]
I can confirm, `'dddd'` doesn't work in `arrow.get` as expected. The result is always the same for any week day.

```python
In [3]: arrow.get('Tuesday', 'dddd')
Out[3]: <Arrow [0001-01-01T00:00:00+00:00]>

In [4]: arrow.get('Sunday', 'dddd')
Out[4]: <Arrow [0001-01-01T00:00:00+00:00]>
```

**Comment by smirnoffs** [comment]
The question now should it work at all? Does it make any sense to parse the weekday without a month, day and year? What date should be used? The first Tuesday AD of the most recent Tuesday?

**Comment by Syeberman** [comment]
If this is to work at all, it should absolutely be the first Tuesday on or after the epoch.

Defaulting to a "most recent Tuesday" scheme would cause surprising results.  Imagine parsing a file around midnight that references "Tuesday" twice, and the second parse occurs on a different day than the first.

**Comment by oakt** [comment]
Can we work on this bug?

**Comment by systemcatch** [comment]
I tend to think this shouldn't work at all, @jadchaar what do you think?

**Comment by jadchaar** [comment]
This is a peculiar use case, but I nonetheless put a quick patch together to fix it.
