### ISSUE TITLE
Odd parsing from list of formats

### ISSUE THREAD

**Issue by richyvk** [crsmithdev/arrow#447]
My test script:

```
date_formats = ['MM/DD/YYYY', 'YYYY-MM-DD', 'X', 'DD-MMMM-YYYY', 'D MMM YYYY']

while True:
    date_to_find = input("Enter date to parse: ")
    parsed_input = arrow.get(date_to_find, date_formats)
    print(parsed_input, ' -- ', parsed_input.timestamp)
```

Sample output:

```
Enter date to parse: 07/15/2000
2000-07-15T00:00:00+00:00  --  963619200
Enter date to parse: 2000-07-15
2000-07-15T00:00:00+00:00  --  963619200
Enter date to parse: 963619200
2000-07-15T00:00:00+00:00  --  963619200
Enter date to parse: 15-July-2000
1970-01-01T00:00:15+00:00  --  15
Enter date to parse: 15 Jul 2000
1970-01-01T00:00:15+00:00  --  15
```
Seems not to like months as words. Is this normal?

**Comment by lightlace** [comment]
Hi richyvk!

Do you really need the "date_formats" array?
I've edited your code a little bit:

#!/usr/bin/env/python3

```
import arrow
import datetime

while True:
    date_to_find = input("Enter date to parse: ")
    parsed_input = arrow.get(date_to_find)
    print(parsed_input, ' -- ', parsed_input.timestamp)
```

And then i get this:

```
Enter date to parse: 15-July-2000
2000-01-01T00:00:00+00:00  --  946684800
```

**Comment by richyvk** [comment]
Thanks for that Lightlace. But I think this doesn't work.

From your example the date is wrong no? It should be 2000-07-15 not 2000-01-01

Also, removing the list just raises errors for certain attempted parses - e.g. try 15 Jul 2000 - this errors.

The error says `Could not match input to any of ['YYYY-MM-DD HH:mm'] on '15 Jul 2000'` so it looks like get expects only that format.
