### ISSUE TITLE
Dash Docset - (Wishlist)

### ISSUE THREAD

**Issue by Phuket2** [crsmithdev/arrow#448]
Would be nice if someone with the skills could create a Dash Docset for arrow. I don't have the skills to do it.  Dash, is so convenient for looking up the API calls.
I use arrow in Pythonista 3 (py3.6) iOS app ( I am still a nubie). Just starting to use it in a flask app with flask-restful.
It's a great lib.

**Comment by ramonsaraiva** [comment]
arrow docs are available here arrow.readthedocs.org - it is unviable to create any other type of documentation right now
