### ISSUE TITLE
arrow.shift(weekday=0) not working in arrow 0.10

### ISSUE THREAD

**Issue by msde** [crsmithdev/arrow#450]
It looks like this was added in https://github.com/crsmithdev/arrow/pull/389 and new docs were released to http://arrow.readthedocs.io, but there's no arrow 0.11 release yet.

**Comment by ramonsaraiva** [comment]
As you said, the feature was merged but the docs are newer than the latest version in pypi `0.10`. We will be working on bumping it soonish.

**Comment by AlJohri** [comment]
@ramonsaraiva just ran into this as well

**Comment by msde** [comment]
Still impacted by this.
