### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by LaurensBosscher** [crsmithdev/arrow#451]
@crsmithdev 

Last commit is on 21 January, the're 21 open pull requests and the last PyPI release is from 2016-11-30.

I have not seen a response from on Pendulum [critique](https://github.com/sdispater/pendulum) of Arrow either while I think he has some valid points (I've opened an issue about this before but I haven't received a reply either). If no further development of Arrow is plannend it might be worth updating the readme to redirect users to an alternative or trying to find a new maintainer.

If further development is plannend (but delayed) it might be worth it to add a note to the readme that this project is still alive (and kicking!) but that response to issues/pull-requests might (temporarily) might take a bit longer.

**Comment by fikrishah** [comment]
Tried to perform _pip install arrow_ using Anaconda 4.4.1  with Python 3.6.1 but failed to get this installed. Any suggestion or hint?

**Comment by jaapz** [comment]
@fikrishah report a new issue and mention whatever error you're getting

**Comment by andrewelkins** [comment]
Project is still alive. We've recently added a couple collaborators to go through the issues & PRs. We should start seeing releases and updates.
