### ISSUE TITLE
Format escape characters

### ISSUE THREAD

**Issue by PaulMuriithi** [crsmithdev/arrow#460]
I am trying to format `2017-03-31 11:58:07 UTC` to `31 Mar 2017 at 14:58PM` but I having issues escaping the `at`.

The date format I am using is `DD MMM YYYY [at] HH:mmA` but the `at` seems not to be escaped because the output I am getting is `31 Mar 2017 [pmt] 14:58PM`

I am using `arrow==0.10.0`

I am cognizant of a similar [PR](https://github.com/crsmithdev/arrow/pull/290) but it seems not to have fixed the format.

**Comment by ramonsaraiva** [comment]
Arrow currently does not support formatting dates like that.
In the PR you mentioned, you can parse dates, but not format them, for example:

```
>> arrow.get(
>>    'September 20th was a beautiful day, specially at 11:58am',
>>    'MMMM Do [was a beautiful day, specially at] HH:mma')

<Arrow [0001-09-20T11:58:00+00:00]>
```

The approach for formatting them would be probably similar, was also requested a long time ago but not tackled yet https://github.com/crsmithdev/arrow/issues/35

**Comment by PaulMuriithi** [comment]
I understand.
