### ISSUE TITLE
Tzinfo will not be preserved when I am using Arrow.get()

### ISSUE THREAD

**Issue by jiangxiluning** [crsmithdev/arrow#462]
Hi, My timezone is 'Asia/Shanghai', The following code gave me wrong timezone
```python
In [46]: c = arrow.get('2017-09-28 21:02:19', tzinfo=tz.tzlocal())

In [47]: c.tzinfo
Out[47]: tzutc()
```

**Comment by jiangxiluning** [comment]
I figured out that when you used "parser" to try to parse the date time string, you lost the tzinfo. But when I hinted you the format.
```python
In [55]: c = arrow.get('2017-09-28 21:02:19.000', 'YYYY-MM-DD HH:mm:ss.SSS', tzinfo='local')

In [56]: c.tzinfo
Out[56]: tzlocal()
```

**Comment by Syeberman** [comment]
Yes, this is definitely confusing!  We're going to be looking into improving `get`, but in the meantime you can use `replace` everywhere you would use `get(..., tzinfo=xxx)`, like this:

```python
c = arrow.get('2017-09-28 21:02:19').replace(tzinfo=tz.tzlocal())
```

No matter how you call `get`, `replace` will always override the timezone returned.

**Comment by jiangxiluning** [comment]
Thanks.
