### ISSUE TITLE
No obvious way to interpret timestamp string as anything other than UTC

### ISSUE THREAD

**Issue by smontanaro** [crsmithdev/arrow#479]
I've pored through the documentation and tried all sorts of things, but I've as yet been unable to get arrow.get() to interpret a timestamp string as anything other than UTC. The default behavior works fine:

> >>> arrow.get("2017-11-07T05:15:00")
> <Arrow [2017-11-07T05:15:00+00:00]>

unless you're doing something nutty like parsing timestamps from some sort of directory listing (my immediate use case is the output of "aws s3 ls"). I tried a couple obvious keyword arguments, tz and tzinfo, but they were silently ignored (which itself seems like a buglet):

> >>> arrow.get("2017-11-07T05:15:00", tz="America/Chicago")
> <Arrow [2017-11-07T05:15:00+00:00]>

This is especially frustrating because I can pass a timezone string (a full-blown timezone object isn't required) to arrow.get() when passing a naive datetime object:

> >>> arrow.get(datetime.datetime.now(), "America/Chicago")
> <Arrow [2017-11-07T06:34:02.828587-06:00]>

It seems like specifying the timezone for an otherwise naive timestamp string should be about as easy, and featured in the list of possibilities in the arrow.factory.ArrowFactory documentation. I realize the two-string case is (timestamp, format), but a keyword arg specification seems fine to me.

If this is trivial, can it be better documented? If it's not trivial (or at least, more involved than the naive datetime case), let me know and I'll see if I can work up the necessary pull request.

**Comment by smontanaro** [comment]
I figured out one way to accomplish my task, though it required reading the source:

> >>> arrow.get("2017-11-07T05:15:00 America/Chicago", "YYYY-MM-DDTHH:mm:ss ZZZ")
> <Arrow [2017-11-07T05:15:00-06:00]>

Searching for "ZZZ" in the docs, I stumbled on the description of how it differs from "Z" and "ZZ". It would be great if the beginners' examples could be augmented with an example like the above.

**Comment by smontanaro** [comment]
I forked and pushed a couple changes. I created a pull request after the first change to help for ArrowFactory:

https://github.com/crsmithdev/arrow/commit/65d5d7439258242842b180654bee83e68c462bcd

I then implemented the suffix tz name for ISO-8601 timestamp strings and pushed that:

https://github.com/crsmithdev/arrow/commit/980a1b44e1e12fa5ed755fce4925e8aa1aca190a

I didn't expect the system to automatically tack on the second commit to the pull request, but there you have it. They are aimed at the same general problem, but offer two different ways to solve it.

**Comment by pganssle** [comment]
Relevant to this: https://stackoverflow.com/questions/42194571/identifying-time-zones-in-iso-8601

And (from the comments): https://www.iso.org/news/2017/02/Ref2164.html

**Comment by pganssle** [comment]
Note that without the full ISO-8601 string with offset (`-05:00` or similar), you potentially have an ambiguous datetime, which is not an ideal situation.

**Comment by smontanaro** [comment]
Thanks for the references. I freely admit that I'm just trying to solve an
ambiguous problem. I can live with the first patch (tacking on ZZZ to a
specific format). Since much of arrow's attraction is simplifying the most
common date/time tasks, I thought the possibility of easily adding an Olson
timezone name would be handy.

As you might surmise by the time of year this problem popped up, I was
burned slightly by the recent DST change. I had been using numeric offsets
and a simple script broke across the change. So, while numeric offsets are
what ISO-8601 supports, they are hardly perfect in a DST world. I would be
happy if everything emitted times in UTC, but ambiguous local time is a
fact of life. It would be great if arrow.get() supported an almost trivial
way of saying, "this should be interpreted in local time."

Apologies for droning on...

**Comment by mikenerone** [comment]
IMO this is still a valid RFE. It seems to me the main use case is when you're _not_ specifying new representations, but are stuck with someone else's existing one. E.g. in my case, I need to parse a naive timestamp from a remote service outside my control, but I do happen to know the (non-UTC) timezone used by that service. I agree that the service's representation is naive, but I can't do anything about that.

**Comment by systemcatch** [comment]
@mikenerone 

Is this what you're trying to do?

```shell
>>> arrow.get("2017-11-07T05:15:00", tzinfo="America/Chicago")
<Arrow [2017-11-07T05:15:00-06:00]>
```

**Comment by systemcatch** [comment]
I'm closing this for now based on my last post, let me know if there's still problems.
