### ISSUE TITLE
Allow parsing of duration strings 1y2w3d4h5m6s

### ISSUE THREAD

**Issue by apnewberry** [crsmithdev/arrow#490]
It'd be nice to parse duration strings like this 1y2w3d4h5m6s. Is that likely possible in Arrow?

**Comment by Syeberman** [comment]
I would lean towards "no".  In general, Arrow deals with moments in time, not durations.

**Comment by ABitMoreDepth** [comment]
A slight change to the originally suggested format would allow arrow to support [ISO8601 Duration fields](https://en.wikipedia.org/wiki/ISO_8601#Durations), which one of my current projects could benefit from.

Would you accept a pull request for that functionality?

**Comment by apnewberry** [comment]
@ABitMoreDepth FWIW, I ended up finding the feature in [Pendulum](https://pendulum.eustace.io/)

```python
In [2]: pendulum.parse('P2Y3M4DT5H6M7S')                                                                                                                                                                                                                                                               
Out[2]: Duration(years=2, months=3, days=4, hours=5, minutes=6, seconds=7)
```
