### ISSUE TITLE
missing dependency when installing from git on python2

### ISSUE THREAD

**Issue by Mn0491** [crsmithdev/arrow#491]
when I did
`pip install git+git://github.com/crsmithdev/arrow.git@b33925e9ce55c3544afcb66a0ffb205593b49ab7` 

I had an error that backports.functools_lru_cache was missing. 

`pip install backports.functools_lru_cache` solved the problem. This is for python 2.7.2

**Comment by jaapz** [comment]
does the same happen when you don't install from git?

**Comment by Mn0491** [comment]
No, it did not ask for that on `pip install arrow`. But the reason why I did it via git, was because the pip install does not currently have the updated code for masters. for example. 

```python 
arrow.now().shift(weekday=5)
```

throws an attribute error.

**Comment by ramonsaraiva** [comment]
Fixed on https://pypi.python.org/pypi/arrow/0.12.0 - please upgrade arrow if you're using python 2.x and arrow 0.11.0
