### ISSUE TITLE
add python 3.6 to the support list

### ISSUE THREAD

**Issue by joelb123** [crsmithdev/arrow#494]
I develop against python 3.6.

My dependency checker let me know that arrow 0.11 is out, but pip doesn't want to let me use it because of restrictions to python 3.5.  Version 0.10.0 worked just fine for me under Python 3.6 and had no restrictions. 

Please add python 3.6 to the list of supported python versions.

**Comment by AlJohri** [comment]
Bump. Can you add the trove classified for Python 3.6?

**Comment by Syeberman** [comment]
We have a PR up to do just that: https://github.com/crsmithdev/arrow/pull/472.

**Comment by AlJohri** [comment]
Thank you!

**Comment by systemcatch** [comment]
Python 3.6 is now supported!
