### ISSUE TITLE
backports.functools-lru-cache

### ISSUE THREAD

**Issue by papachoco** [crsmithdev/arrow#497]
Hello,,

Is there any way arrow could use backports.functools-lru-cache 1.4 (latest) for python 2.7

Carlos

**Comment by pablogamboa** [comment]
I'm bitten by this as well, the installed version must be 1.4, otherwise import fails after upgrading to arrow 0.12

**Comment by threegirl2014** [comment]
I met this bug as well...

**Comment by Syeberman** [comment]
@threegirl2014, are you using the latest version of Arrow from pip?  I just checked version 0.12.1 and it contains the following, which should allow for newer releases of `backports.functools_lru_cache`.

```
    extras_require={
        ":python_version=='2.7'": ['backports.functools_lru_cache>=1.2.1'],
    },
```

**Comment by threegirl2014** [comment]
@Syeberman 
In some Linux OS, the default pip version is 1.5.4.  
After running 'pip install arrow', it can not install the requirements correctly just like backports.functools_lru_cach.

But if the pip version is 9.0.1, it works.

**Comment by systemcatch** [comment]
see #495 for further discussion on this.
