### ISSUE TITLE
Conditioning install_requires against sys.version_info does not work for wheels

### ISSUE THREAD

**Issue by yalinhuang** [crsmithdev/arrow#506]
If python3 is used to build a wheel, the `if sys.version_info[0] < 3:` (in [setup.py](https://github.com/crsmithdev/arrow/blob/master/setup.py#L30)) would be `False`. The built wheel cannot be used for python2 while, unfortunately, pip does not distinguish py2/py3 wheel.

Instead, `extras_require` should be the option here to put predicates that would be evaluated during runtime (instead of build time). An example is how [websocket-client does this type of task](https://github.com/websocket-client/websocket-client/blob/master/setup.py#L17); also [this blog explains](https://hynek.me/articles/conditional-python-dependencies/).

**Comment by systemcatch** [comment]
This was fixed in 61f4808d5f6bb116b5952b90b9c838e81a26e8b9
