### ISSUE TITLE
Use Delimiters for arrow.format()

### ISSUE THREAD

**Issue by XIncognito10** [crsmithdev/arrow#514]

**Comment by Syeberman** [comment]
@XIncognito10, can you provide more information?

**Comment by XIncognito10** [comment]
Currently, the format method uses the tokens without any way for other text to be entered because arrow has no way of knowing what's a token and what's other text that the user wants to just be repeated literally. For example. if I wanted to get a formatted string like January 5, 2018 at 10:16PM, I couldn't write:

MMMM D, YYYY at hh:mma

because arrow would parse the 'a' in 'at' and you would end up with

January 5, 2018 PMt 10:16PM

There's no way for arrow to know that 'at' should be written literally. 

would it be possible to tell arrow to ignore a particular character? for example by escaping it with a special character or by having all the tokens require a character to state that this is in fact a token?

**Comment by XIncognito10** [comment]
the former would probably be the best solution since it is backwards compatible, but since using the back slash already escape characters in python, some other character would be needed. My personal suggestion would be to surround the characters to escape with the backtick sign since most people use an single quote instead. You could even use 2 backtics to prevent accidental parsing. for example

MMMM D, YYYY ``at`` hh:mma

which would give 

January 5, 2018 at 10:16PM

**Comment by Syeberman** [comment]
Thanks for the suggestion @XIncognito10, but there's another way to accomplish what you need:

```python
>>> import arrow
>>> ar = arrow.get(2018, 1, 5, 22, 16)
>>> '{0:MMMM D, YYYY} at {0:hh:mma}'.format(ar)
'January 5, 2018 at 10:16pm'
```

This is even easier with Python 3.6's [F strings](https://www.slideshare.net/MariattaWijaya/f-strings-76440081):

```python
>>> f'{ar:MMMM D, YYYY} at {ar:hh:mma}'
'January 5, 2018 at 10:16pm'
```

I'd rather not complicate our formatting language further when acceptable alternatives already exist.
