### ISSUE TITLE
`somearrow.strftime('%s')` uses local timezone, not `somearrow`'s timezone

### ISSUE THREAD

**Issue by AdamWill** [crsmithdev/arrow#520]
Well, I *think* this is wrong. Here's a test script:

    import arrow

    sometime = arrow.get('2017-01-01 12:00')
    print(sometime.timestamp)
    print(sometime.strftime('%s'))
    print(sometime.strftime('%Y-%m-%d %H:%M:%S'))

Saved as `/tmp/test.py`, here's the output of running it with some different system timezones:

actual system timezone - PST:

    [adamw@xps13k pagure (more-timezone-fun %)]$ python /tmp/test.py
    1483272000
    1483300800
    2017-01-01 12:00:00

UTC:

    [adamw@xps13k pagure (more-timezone-fun %)]$ TZ='UTC' python /tmp/test.py
    1483272000
    1483272000
    2017-01-01 12:00:00

Winnipeg (why not?):

    [adamw@xps13k pagure (more-timezone-fun %)]$ TZ='America/Winnipeg' python /tmp/test.py
    1483272000
    1483293600
    2017-01-01 12:00:00

Note that the arrow's `timestamp` attribute and the `strftime('%Y-%m-%d %H:%M:%S')` output is the same regardless of the system timezone, which I'd expect: arrows are UTC by default. But the output of `strftime('%s')` varies by system timezone, which I did *not* expect. I would expect it to always be the same as the `timestamp` attribute.

After noticing this in arrow I checked and in fact the bug exists in Python's own datetime, for aware datetime instances: I filed that as [Python bug 32988](https://bugs.python.org/issue32988). So if arrow is just handing `strftime` duties off to `datetime` behind the scenes, this is essentially the same as that bug, I guess. Still figured it'd be worth reporting.

**Comment by AdamWill** [comment]
Update: there's quite a lot about this at [Python issue 12750](https://bugs.python.org/issue12750).

**Comment by systemcatch** [comment]
Hey thanks for pointing out those bug threads, interesting reading.

You're correct that arrow hands off strftime duties to datetime (https://github.com/crsmithdev/arrow/blob/master/arrow/arrow.py#L1135) so we can't do much about this here.
