### ISSUE TITLE
Formatter can't format Timezone name using "ZZZ"

### ISSUE THREAD

**Issue by boarik** [crsmithdev/arrow#523]
Example code:
```
dt = arrow.get("2018-03-19 13:55:44 US/Pacific", "YYYY-MM-DD HH:mm:ss ZZZ")
dt.format("YYYY-MM-DD HH:mm:ss ZZZ")
```
Expected output:
`"2018-03-19 13:55:44 US/Pacific"`

Actual output:
`"2018-03-19 13:55:44 -07:00-0700"`

**Comment by boarik** [comment]
And now I see this issue has a pending PR: https://github.com/crsmithdev/arrow/pull/391

**Comment by systemcatch** [comment]
@boarik I merged that PR so hopefully this is fixed in the next release.
