### ISSUE TITLE
EU format question

### ISSUE THREAD

**Issue by addisonp** [crsmithdev/arrow#534]
I was just wondering if anyone had taken into consideration the way some EU institutions still use the DD.MM.YYYY format?  I have actually come across some instances that use this format and was wondering if it would be useful to add that to arrow's automated detection?  I would love to do it and add it to the arrow codebase if it is something that would be helpful to others instead of using arrow.get(data, 'DD.MM.YYYY').

**Comment by systemcatch** [comment]
Hey I know it's been a while but if you still feel like doing this then by all means go for it.

**Comment by jadchaar** [comment]
@systemcatch if we were to implement this, couldn't the `DD` and `MM` be ambiguous?

**Comment by systemcatch** [comment]
@jadchaar you're right this would probably not be a good format to try by default.
