### ISSUE TITLE
ceil() not work as I want

### ISSUE THREAD

**Issue by zgfh** [crsmithdev/arrow#542]
```
get next year 
next_year=arrow.get(1514736000).to('Asia/Shanghai').ceil('year')
<Arrow [2018-12-31T23:59:59.999999+08:00]>
get next year of next year 
arrow.get(1514736000).to('Asia/Shanghai').ceil('year').ceil('year')
<Arrow [2018-12-31T23:59:59.999999+08:00]>
```

**Comment by n3storm** [comment]
http://arrow.readthedocs.io/en/latest/#replace-shift

Next dates should be done via replace method:
```
this_year = arrow.utcnow().floor('year')
next_year = this_year.replace(year=+1)
next_next_year = next_year.replace(year=+1)
```
Not sure why you are using ceil (end of the year) instead of floor (begining of the year)

**Comment by zgfh** [comment]
thanks for help.
I have use floor to make it work:
```
arrow.get(1514736000).to('Asia/Shanghai').floor('year').shift(years=1)
```
and,Does `arrow.get(1514736000).to('Asia/Shanghai').ceil('year').ceil('year')` and `arrow.get(1514736000).to('Asia/Shanghai').ceil('year')` return the same result as expected?

**Comment by jaapz** [comment]
@n3storm The code you've given would set the year to year 1, instead of adding 1 to the current year in the date. You should either use `.replace(years=+1)` (notice the `s` in `years`), and preferably use `shift` instead of `replace`.

**Comment by systemcatch** [comment]
There's no bug here and advice has been given to improve your code.
