### ISSUE TITLE
microsecond precision simulation?

### ISSUE THREAD

**Issue by maludwig** [crsmithdev/arrow#543]
I'm not sure this is a good idea, but, on Windows, with Python 3.6 at least, there is no microsecond precision on Python's implementation of datetime.datetime.utcnow(), and as a result, Arrow also doesn't have that precision, so on Linux/OSX, this works, but on Windows, it doesn't:

```
arrow1 = arrow.utcnow()
arrow2 = arrow.utcnow()
if arrow1 == arrow2:
  print("Sad and busted on Windows")
else:
  print("Yay! Linux microsecond precision!")
```

In order to make timestamps linear, I've made a function that adds an ever increasing number:

```
last_unix_timestamp = time.time()

def linear_utc_now():
    global last_unix_timestamp
    this_unix_timestamp = time.time()
    if this_unix_timestamp <= last_unix_timestamp:
        this_unix_timestamp = last_unix_timestamp + 0.000001
    last_unix_timestamp = this_unix_timestamp
    this_arrow = arrow.get(this_unix_timestamp)
    return this_arrow
```

It generates 100000 arrows in 347ms, while arrow.utcnow() generates 100000 in 207ms, so there's a performance hit.

I'm not sure if it's a good idea to add this to arrow, but I thought I'd open it as an issue and if you guys wanted it, it's yours.

**Comment by maludwig** [comment]
Primary upside is that all generated timestamps are linear. Primary downside is that if you generate 1000 in under 1ms (which I can do on my Core i7), they start wandering farther into the future than what reality is. They take longer to generate, and they are kinda hacky.

**Comment by maludwig** [comment]
Waitwait, the above is a terrible solution. Forget it.

Ok so, there's a new thing in Python 3.7: https://www.python.org/dev/peps/pep-0564/
The function names promise nanosecond precision, but it turns out that that's actually wild optimism. It also turns out that the extra math involved in converting from int nanoseconds to float seconds is slower than the native float implementations.

So there's a thing for measuring performance, built into Python. It gives really good, really granular precision, but its timestamps are based on a flexible epoch. So on different OSes, it will give different values at a given point in time. BUT, the epoch is fixed from the first call to the function. So that if you call the function twice, you can measure the difference between those two times. AND if you call the function 1000 times, you can measure the difference between any two given calls.

So, without being freaky, we actually can generate high granularity accurate timestamps very quickly.

This gist is a demo file, trying out many different high resolution generation methods. It tests all of the ideas I had so far and prints the performance results:
https://gist.github.com/maludwig/9fc724af03e8a349e34500630c3c2875

The fastest one conveniently does not require the ns methods from Python 3.7:
```

initial_perf = time.perf_counter()
initial_time = time.time()
perf_time_offset = initial_time - initial_perf

def perf_counter_datetime_method():
    global perf_time_offset
    timestamp_in_secs = time.perf_counter() + perf_time_offset
    dt = datetime.datetime.utcfromtimestamp(timestamp_in_secs)
    return arrow.Arrow.fromdatetime(dt)
```

The one downside is that it's slightly slower than arrow.utcnow(), on my computer, arrow.utcnow() can make 498 Arrows in 1ms. But the method above can only do 440.

I'm gonna try it on Linux and OSX.

**Comment by jadchaar** [comment]
Hey @maludwig, feel free to reopen this if you would like to provide some extra info.
