### ISSUE TITLE
 Could not parse timezone expression "JST"

### ISSUE THREAD

**Issue by houyingkun** [crsmithdev/arrow#549]
test_str = '2018/07/01 01:00:17JST'
test_format = 'YYYY/MM/DD HH:mm:ssZZZ'
locale = 'ja'
print(arrow.get(test_str, test_format, locale=locale))

And it except an exception:
arrow.parser.ParserError: Could not parse timezone expression "JST"
Is it a bug?

**Comment by systemcatch** [comment]
In the docs (https://arrow.readthedocs.io/en/latest/#tokens) it says that arrow uses timezone names from the tz database provided by dateutil.

```python
>>> import dateutil
>>> from dateutil.zoneinfo import get_zonefile_instance
>>> zonenames = list(get_zonefile_instance().zones)
>>> for z in zonenames:
...     print(z)
```
'JST' is not in there hence the failure.

**Comment by systemcatch** [comment]
Closing this as we can't help here.
