### ISSUE TITLE
Interactive demo for `arrow` code examples

### ISSUE THREAD

**Issue by martinzugnoni** [crsmithdev/arrow#556]
Hello @crsmithdev,

I've been using `arrow` lately and found it really interesting. We're also evaluating to include it in our curriculum at https://rmotr.com/ (co-founder and teacher here). It's cool to show `arrow` (and also other libraries) in comparison to the built-in `datetime` module.

While looking at the code examples in the README file I thought it would be great to provide some interactive demo that people can use to play with the library before committing to download and install it locally.

> A demo is worth a thousand words 😉

I spent some time compiling all `arrow` examples into a Jupyter Notebook file, and adapted it in a way that we can open it with a small service we have at RMOTR to launch Jupyter environments online. No signup required to use it, so it's pretty convenient for people that wants to get hands on the library with a low entrance barrier. Note that `arrow` is already installed when the env is loaded, so people can start using it right away.

The result is what you can see in my fork of the repo (see the new "Demo" section):
https://github.com/martinzugnoni/arrow

Do you think that having such interactive demo would help people to know and use `arrow`?
Let's use this issue as a kick off to start a discussion. Nothing here is written in stone and we can change everything as you wish.

I hope you like it, and I truly appreciate any feedback.

thanks.

**Comment by systemcatch** [comment]
@martinzugnoni thanks for the idea. On a brief pass over it looks interesting, though when I saw it all of the code seemed to have already run, maybe this is expected though. I'm not going to have much time to get to this soon but we'll keep an eye on it.

The question is does this provide much benefit to first time users of arrow? I wouldn't really use this but others might, we need input from them.

**Comment by martinzugnoni** [comment]
Hey @systemcatch, did you have some time to check the DEMO Notebook in more detail? I would love to hear some feedback and also define if it makes sense to move forward in this direction. If so, I would be happy to put some extra effort and time to make the integration and create the associated PR. Please confirm me if I should start with it ;-)

**Comment by crsmithdev** [comment]
@martinzugnoni thanks for the demo, that's really interesting.  As much as I like it, I'm not sure it makes sense to integrate it directly into arrow with a PR.

**Comment by martinzugnoni** [comment]
@crsmithdev sounds good! Let me know if there's any other way you see to implement such an interactive demo. Cheers.
