### ISSUE TITLE
Publish .whl file to PyPI

### ISSUE THREAD

**Issue by jaycle** [crsmithdev/arrow#558]
Being a pure python library and containing the `[bdist_wheel]` attribute in `setup.cfg` this library is already ready to generate .whl files which are the [preferred packaging format](https://www.python.org/dev/peps/pep-0427/). Currently, arrow is my only dependency that doesn't publish a wheel file to PyPI and this creates some deployment complications for some serverless frameworks (namely Azure). Since the file can be generated as simply as
```
python setup.py sdist bdist_wheel
```
it would be good to have this library on the list at https://pythonwheels.com/.

**Comment by systemcatch** [comment]
Seems like an easy thing we should do for the future, I don't know if it's possible to add wheels for the older releases as well?

I don't have publish access to PyPi so this is something @crsmithdev would have to do.

**Comment by systemcatch** [comment]
@jaycle arrow 0.13.1 has now been released and is the first version to include a wheel on PyPi!  All later versions will include them.
