### ISSUE TITLE
Test failure: ArrowIntervalTests

### ISSUE THREAD

**Issue by alucryd** [crsmithdev/arrow#559]
Hi there, I'm getting a test failure trying to bump the Arch Linux package, see https://paste.xinu.at/QNtC/

This test fails with Python 3 only, not Python 2.

Our current versions:
* Python 3: 3.7.2
* Python 2: 2.7.15
* Chai: 1.1.2

Please let me know if you need anything else.

**Comment by systemcatch** [comment]
Hello @alucryd, arrow does not support python 3.7 yet but it's being implemented in #544. The test failure is due to Stopiteration being replaced by RuntimeError in 3.7

**Comment by alucryd** [comment]
Thanks a lot for your quick answer! I'll probably backport the PR then, thanks for pointing me to it.

**Comment by systemcatch** [comment]
hey @alucryd, just to let you know that the new version of arrow (0.13.1) now supports python 3.7.

**Comment by alucryd** [comment]
Thanks for the heads up! I just updated the Arch Linux package.
