### ISSUE TITLE
Confusion around arrow and arrow_fatisar

### ISSUE THREAD

**Issue by jamiejackherer** [crsmithdev/arrow#563]
I was unsure where to ask this so I just thought I'd ask here, apologies if this is wrong. 

While using pyreqs to make a requirements.txt the arrow package was put into requirements as arrow_fatisar. but i have not install arrow_fatisar only arrow, I see the maintainer is the same person but the name is different and the versions are different. I am a bit confused about 2 things:

1) whats the difference between them?
2) Why would pyreqs do this when I do't actually have arrow_fatisar installed?

(Quick side note, amazing package, possibly the best and most simple human readable time package around - good work!)

**Comment by systemcatch** [comment]
Hello @jamiejackherer, glad you find the package useful.

1. arrow_fatisar seems to be a fork of arrow (https://github.com/fatisar/arrow), long abandoned from the looks of it.
2. I have no idea how pyreqs (https://github.com/rmad17/pyreqs) works, best to ask there.

**Comment by jamiejackherer** [comment]
I will have a look at the code to see how pyreqs gathers it's names. I was more interested in the seemingly same package with different versions, I'm sure it said the maintainer was the same just wondered if may  there was a difference for any reason. Thanks
