### ISSUE TITLE
Local date

### ISSUE THREAD

**Issue by alexvasiliev** [crsmithdev/arrow#566]
`arrow.get(smth).replace(tzinfo='local').day` and `arrow.get(smth).replace(tzinfo='local').format('HH:DD.MM.YYYY')` will give you day in utc, not in local timezone.   
Is it possible to get human date and time in local timezone?

**Comment by systemcatch** [comment]
I don't understand what you mean, please provide an example with current output and what you would like instead.

**Comment by alexvasiliev** [comment]
So, `arrow.get(1547500000).replace(tzinfo='Europe/Moscow').day` will give me 14. And i would like to get 15. (Because it is already 15.01.19 in +3 tz, but 14.01.19 in +0)

**Comment by systemcatch** [comment]
Oh ok now I understand what you mean. replace() will simply swap whatever attribute is specified without changing anything else. Here is how I'd do this.

```shell
>>> arrow.get(1547500000).to('Europe/Moscow')
<Arrow [2019-01-15T00:06:40+03:00]>
```

or using a tzinfo object;

```shell
>>> mt
tzfile('/usr/share/zoneinfo/Europe/Moscow')
>>> arrow.Arrow.fromtimestamp(1547500000, mt)
<Arrow [2019-01-15T00:06:40+03:00]>
```
