### ISSUE TITLE
Business day support 

### ISSUE THREAD

**Issue by Taschenbergerm** [crsmithdev/arrow#568]
I would love to see a business day support in arrow. or a Simple adjustment in the add and subtract s.t. the would allow for pandas.tseries.offsets BDay would be really helpful. 
currently, there is an ugly way like 
```
import arrow
from pandas.tseries.offsets import BDay
arrow.get(arrow.get().date() - BDay(1))
```

awesome would be  
```
import arrow
from pandas.tseries.offsets import BDay
arrow.get() - BDay(1)
```

Thanks

**Comment by dyerd** [comment]
@Taschenbergerm I submitted a pull request with a method to add and subtract business days from dates. Was there any other business day support you'd like to see in arrow?

**Comment by Taschenbergerm** [comment]
@dyerd Thanks for the work and effort. This would cover my use case. 

Think one step further - do you think it would make sense to also apply the business day logic to functionalities such as the date-range or date-span?

**Comment by systemcatch** [comment]
Hi @Taschenbergerm, @dyerd, my apologies for not responding to this issue sooner.

I've spoken to @crsmithdev and we're both of the opinion that this isn't something that makes sense to have in the library itself.
