### ISSUE TITLE
Date Range not working with inner for loop

### ISSUE THREAD

**Issue by crhyatt** [crsmithdev/arrow#569]
When using a a date range in 0.13.1 in inner for loop the second time will not execute.

for something in group_of_things:
    for week in date_range:
        will not reach here on the second something

**Comment by systemcatch** [comment]
I don't understand what you're saying, please provide a working code example of the problem.

**Comment by crhyatt** [comment]
>>>
>>>import arrow
>>> from_date = arrow.get("2017-09-11T00:00:00+0000").floor('week').timestamp
>>> to_date = arrow.get("2017-09-24T23:59:59+0000").ceil('week').timestamp
>>> raw_from = arrow.Arrow.utcfromtimestamp(from_date).shift(days=+6)
>>> raw_to = arrow.Arrow.utcfromtimestamp(to_date).shift(days=+6)
>>> date_range = arrow.Arrow.range('week', raw_from, raw_to)
>>> for week in date_range:
...     print(week)
...
2017-09-17T00:00:00+00:00
2017-09-24T00:00:00+00:00
>>> for week in date_range:
...     print(week)
...
>>>

**Comment by crhyatt** [comment]
I am using python 3.5.5

**Comment by systemcatch** [comment]
Thanks for the example which I've copied below, can you tell me what output you expect instead?

```shell
Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.13.0'
>>> from_date = arrow.get("2017-09-11T00:00:00+0000").floor('week').timestamp
>>> to_date = arrow.get("2017-09-24T23:59:59+0000").ceil('week').timestamp
>>> from_date
1505088000
>>> to_date
1506297599
>>> raw_from = arrow.Arrow.utcfromtimestamp(from_date).shift(days=+6)
>>> raw_to = arrow.Arrow.utcfromtimestamp(to_date).shift(days=+6)
>>> raw_from
<Arrow [2017-09-17T00:00:00+00:00]>
>>> raw_to
<Arrow [2017-09-30T23:59:59+00:00]>
>>> date_range = arrow.Arrow.range('week', raw_from, raw_to)
>>> for week in date_range:
...     print(week)
... 
2017-09-17T00:00:00+00:00
2017-09-24T00:00:00+00:00
```

**Comment by crhyatt** [comment]
I expect that the second for loop would print the same at the first for loop.

for week in date_range:
... print(week)
...
2017-09-17T00:00:00+00:00
2017-09-24T00:00:00+00:00
for week in date_range:
... print(week)
...

**Comment by systemcatch** [comment]
Oh right now I understand, arrow's range method returns an iterator so once looped over it's gone and can't be reused.

However you can wrap it in a list() to allow reuse.

```shell
>>> date_range = list(arrow.Arrow.range('week', raw_from, raw_to))
>>> for week in date_range:
...     print(week)
... 
2017-09-17T00:00:00+00:00
2017-09-24T00:00:00+00:00
>>> for week in date_range:
...     print(week)
... 
2017-09-17T00:00:00+00:00
2017-09-24T00:00:00+00:00
```
Problem solved?

**Comment by crhyatt** [comment]
> However you can wrap it in a list() to allow reuse.

This was not needed in 0.13.0.  That makes sense now.  I will make the changes to our code bases.  Thank you.

**Comment by systemcatch** [comment]
No problem, you've actually reminded me to put that in the release notes for 0.13.1. As part of the changes required for python 3.7 support we removed some old decorators that were covering this behavior.
