### ISSUE TITLE
The time is unchanged when the server first start?

### ISSUE THREAD

**Issue by bifeng** [crsmithdev/arrow#570]
I am using the arrow.now() function in my question answer system, which deploy on the server. But the time is unchanged when the server first start, example if i start server in 21/2/2019, then the time always is  21/2/2019.

System:
ubuntu

Is there any solution? maybe is not the arrow's problem? or it just retrieve the time from memory?

**Comment by systemcatch** [comment]
Hi you might find that https://stackoverflow.com/a/51111746 answers your question (it is for datetime.now() but the principle is the same).

**Comment by bifeng** [comment]
Thanks!
