### ISSUE TITLE
Change Sphinx documentation theme

### ISSUE THREAD

**Issue by jadchaar** [crsmithdev/arrow#593]
The F6 theme that [we are currently using](https://github.com/crsmithdev/arrow/tree/master/docs/_themes) for the docs does not seem to be maintained anymore and does not play well with modern web standards (e.g. responsiveness on screen resizing). Therefore, I think it is worth it to explore a transition to a more modern and maintained theme such as the [default alabaster theme](https://alabaster.readthedocs.io/en/latest/) in Sphinx.

**Comment by ashwineaso** [comment]
@jadchaar I'd like to take this up. Since I'm new to this, I'd like pointers and guidance. I'll raise a PR once I have an initial version out.

**Comment by jadchaar** [comment]
Hey @ashwineaso, thanks for the contribution and help! I’m currently out of town, but I’ll be back tomorrow and I’d be happy to review the PR :).

**Comment by jadchaar** [comment]
This will be a great upgrade as it will fix the unicode issues we have with the current docs:

![Screen Shot 2019-07-08 at 8 24 27 PM](https://user-images.githubusercontent.com/7388203/60850706-7c226d80-a1be-11e9-8bc5-d5fa46f315f5.png)
