### ISSUE TITLE
setup.py is trying to import dependencies which aren't yet installed

### ISSUE THREAD

**Issue by andrewmwilson** [crsmithdev/arrow#598]
In this recent change (https://github.com/crsmithdev/arrow/commit/2e5031b473bcf10b99b9d7ff8a7e72499c412c07), setup.py now does `from arrow import __version__` which triggers a bunch of other imports. This fails is `python-dateutil` hasn't already been installed.

```
Collecting arrow<1,>=0 (from this-is-redacted==1.2.3->also-redacted==4.5.6)
  Downloading https://files.pythonhosted.org/packages/a0/3b/0b5c7771a619ee4eae1f894669dd5f7c0aae9c92d87891c4c746937f9cc4/arrow-0.14.0.tar.gz (102kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c5xbxqxi/arrow/setup.py", line 4, in <module>
        from arrow import __version__
      File "/tmp/pip-build-c5xbxqxi/arrow/arrow/__init__.py", line 3, in <module>
        from .api import get, now, utcnow
      File "/tmp/pip-build-c5xbxqxi/arrow/arrow/api.py", line 10, in <module>
        from arrow.factory import ArrowFactory
      File "/tmp/pip-build-c5xbxqxi/arrow/arrow/factory.py", line 15, in <module>
        from dateutil import tz as dateutil_tz
    ImportError: No module named 'dateutil'
```

It looks like this issue has come up previously https://github.com/crsmithdev/arrow/issues/120

**Comment by jadchaar** [comment]
@andrewmwilson apologies for this. We will get a fix pushed as soon as possible. Waiting on approval for my fix.

**Comment by andrewmwilson** [comment]
Thanks for the quick response!

**Comment by andrewmwilson** [comment]
Thanks for fixing this so quickly. Should I expect a new release soon with this fix?

**Comment by jadchaar** [comment]
@andrewmwilson yup! We are currently waiting for the creator @crsmithdev to deploy the update to PyPI :). It should occur by the end of today at the latest.

**Comment by jadchaar** [comment]
@andrewmwilson [`arrow` 0.14.1](https://pypi.org/project/arrow/) has been released.

**Comment by andrewmwilson** [comment]
Thanks again for the quick fix 👏 👏 👏

**Comment by andrewmwilson** [comment]
Sorry, referenced wrong issue ⬆️
