### ISSUE TITLE
setup.py needs to specify encoding when reading README.rst

### ISSUE THREAD

**Issue by andrewmwilson** [crsmithdev/arrow#600]
I've found another issue with the recent changes to setup.py (https://github.com/crsmithdev/arrow/commit/2e5031b473bcf10b99b9d7ff8a7e72499c412c07)

Depending on the current locale, installation fails when setup.py attempts to read README.rst
```
Collecting arrow<1,>=0 (from this-is-redacted==1.2.3->also-redacted==4.5.6)
  Downloading https://files.pythonhosted.org/packages/90/7f/7fd8accc23aa507d215b5f07b509661c31583010d8276ba844896ee1f44b/arrow-0.14.1.tar.gz (102kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3mcnwe97/arrow/setup.py", line 7, in <module>
        readme = f.read()
      File "/apps/api/venv_py3/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 3701: ordinal not in range(128)
```

Also see:
https://github.com/crsmithdev/arrow/issues/202
https://github.com/crsmithdev/arrow/issues/208
https://github.com/crsmithdev/arrow/issues/224

**Comment by andrewmwilson** [comment]
Sorry to do this to you @jadchaar!

**Comment by andrewmwilson** [comment]
I will open a PR very shortly.

**Comment by jadchaar** [comment]
No problem @andrewmwilson thanks for bringing this up. Hah the seemingly innocuous change seemed to cause the most issues.

**Comment by jadchaar** [comment]
@andrewmwilson `arrow 0.14.21 has been released to address this issue. Let us know if it fixes the issue and if you have anymore questions or concerns!

**Comment by andrewmwilson** [comment]
Thanks again!
