### ISSUE TITLE
Configure webhook for readthedocs

### ISSUE THREAD

**Issue by systemcatch** [crsmithdev/arrow#606]
If we enable a webhook for the readthedocs (https://docs.readthedocs.io/en/stable/webhooks.html) then that will allow us to automatically build and push docs with each new commit. The benefit is that the docs will stay current with the master branch rather than lagging behind while reducing our workload.

/cc @crsmithdev

**Comment by jadchaar** [comment]
Done!

**Comment by jadchaar** [comment]
Re-opening this, because we actually need a step to be done by @crsmithdev for this to be complete: https://docs.readthedocs.io/en/stable/webhooks.html#github

**Comment by jadchaar** [comment]
Done for real!
