### ISSUE TITLE
Make .get() handle string tzinfo kwarg properly

### ISSUE THREAD

**Issue by systemcatch** [crsmithdev/arrow#625]
With the way factory.get() is currently setup the following happens;

```shell
>>> import arrow
>>> arrow.get(tzinfo='EST')
<Arrow [2019-08-01T18:30:24.799081+00:00]>
```

Essentially .get() is ignoring the tzinfo kwarg if it's not a tzinfo object and just returning .utcnow(). This could produce hard to detect errors imo, I think it should raise an error if the tzinfo kwarg is unused. Since we allow str tzinfo's elsewhere it makes sense to do so here.

@jadchaar any thoughts?

**Comment by jadchaar** [comment]
I don't think we should necessarily raise an error if the tzinfo kwarg is unused, but I do think we should definitely handle the tzinfo of type string properly. Hopefully, all we would need to do is detect that it is a string and then pass it to the locale parser.
