### ISSUE TITLE
Test TzinfoParser against full timezone database

### ISSUE THREAD

**Issue by systemcatch** [crsmithdev/arrow#657]
See https://github.com/crsmithdev/arrow/blob/master/arrow/parser.py#L454

Some ideas on how to do this (https://stackoverflow.com/questions/15453917/get-all-available-timezones), seems like both dateutil and pytz could be used. I tend towards using pytz because it's independent of the operating system and we already use it in other tests.

**Comment by certator** [comment]
I will give it a try 👷
