### ISSUE TITLE
Contructor issue with non-None timezone

### ISSUE THREAD

**Issue by mafycek** [crsmithdev/arrow#658]
Constructor of Arrow object (arrow.py) fails if tzinfo is non-None and if it does not contain field "zone". 

The problematic part:
```python
            isinstance(tzinfo, dt_tzinfo)
            and hasattr(tzinfo, "localize")
            and tzinfo.zone
        ):
```
should be like 
```python
            isinstance(tzinfo, dt_tzinfo)
            and hasattr(tzinfo, "localize")
            and hasattr(tzinfo, "zone")
        ):
```
The change came since version 0.14.5

**Comment by systemcatch** [comment]
Hello @mafycek, I don't understand what you mean, please can you provide a reproducible example.

**Comment by jadchaar** [comment]
Hey thanks for reporting this. Like Chris said, it would be great to have an example input that causes Arrow to fail so we can write a regression test :).

**Comment by mafycek** [comment]
Hi guys, 
hope that you are well.
Say, I have a (simple) program like:
`
import arrow
import dateparser

date_that_succeds = "1990-01-01T00:00:00"
date_that_fails = "1990-01-01T00:00:00+00:00"

for date in [date_that_succeds, date_that_fails]:
    try:
        parsed_date = dateparser.parse(date, date_formats=None or ['%d %B %Y', '%d/%m/%y', '%d/%m/%Y', '%d.%m.%Y'])
        arrow_date = arrow.get(parsed_date)
        print(date_that_succeded, arrow_date)
    except:
        print("It failed on date " + date)
`
Results:
with arrow 0.15.0
The first date passes however the the second fails.
with arrow 0.14.4 (I tested on 0.13.1)
Both pass

Explanation of the failure:
parsed_date is of type _datetime_ with component variable _tzinfo_ of type StaticTzInfo. The StaticTzInfo type has two component variables _StaticTzInfo__name of type str and _StaticTzInfo__offset of type timedelta. When such variable is inserted into **arrow** through _get_ it fails in the constructor of arrow class because tzinfo in the constructor is of type StaticTzInfo that does not have component variable _zone_ and that is why the interpreter says 
AttributeError: 'StaticTzInfo' object has no attribute 'zone'

My comment:
I do not know if the test of zone component is correct. If yes that it should test presence of the variable and then the value if that is needed.

Bye,
Hynek

**Comment by mafycek** [comment]
Colleague of mine fixed unnecessary stuff and typo. However the message is the same:
`
import arrow
import dateparser

date_that_succeeds = "1990-01-01T00:00:00"
date_that_fails = "1990-01-01T00:00:00+00:00"

for date in [date_that_succeeds, date_that_fails]:
    try:
        parsed_date = dateparser.parse(date, date_formats=['%d %B %Y', '%d/%m/%y', '%d/%m/%Y', '%d.%m.%Y'])
        arrow_date = arrow.get(parsed_date)
        print(date, arrow_date)
    except:
        print("It failed on date " + date)
`

**Comment by systemcatch** [comment]
Thanks @mafycek, we will do some digging on this bug and look at fixes.
