### ISSUE TITLE
Add support for humanizing a rate

### ISSUE THREAD

**Issue by bmintz** [crsmithdev/arrow#666]
I found myself needing to humanize a rate, like "2.1 events per second". I wrote a function that does this for English:

```py
def natural_rate(delta: Union[float, datetime.timedelta]):
    """return an english string representing a rate. delta is assumed to be a rate as "1 per delta"."""
    if isinstance(delta, datetime.timedelta):
        delta = delta.total_seconds()
    rate = 1 / delta
    for i, multiplier in enumerate((1, 60, 60, 24, 7)):
        rate *= multiplier
        if rate > 1:
            break
    duration = ('second', 'minute', 'hour', 'day', 'week')[i]
    return f'{rate:.2g} per {duration}'
```

However it would be really nice if arrow supported this with locale translation.

**Comment by jadchaar** [comment]
This sounds like an awesome feature! If you'd like to submit a pull request with this feature, we'd be more than happy to take a look. Any help is appreciated :).

**Comment by bmintz** [comment]
@jadchaar I will try. Not sure to do the i18n stuff though.

**Comment by bmintz** [comment]
I'm also not sure what the API should look like. I think it makes the most sense as a top level function `arrow.humanize_rate(delta: datetime.timedelta)`. `Arrow#humanize_rate` doesn't feel right to me. I don't think of a rate as "two datetimes".

**Comment by jadchaar** [comment]
@systemcatch what do you think the interface should look like?

**Comment by systemcatch** [comment]
@bmintz To be honest I think something like this is best outside a library. We probably won't implement this unless there's high demand for it. You can import from arrow's locales module to get any translations you need.

**Comment by systemcatch** [comment]
@iomintz ok fair enough on the translations, can you give me a specific example where the phrasing differs? Also an example of your function in action.

**Comment by systemcatch** [comment]
Yes but what exactly is `emote_usage_interval` when it's passed to `natural_rate`, I need to see the exact format like this;

```python
natural_rate(324.43, locale=current_locale.get())
"2.1 events per second"
```
