### ISSUE TITLE
Formatter needs to handle [text_blocks]

### ISSUE THREAD

**Issue by snoopyjc** [crsmithdev/arrow#680]
The formatter also needs to handle [text_blocks], not just the parser, to support things like:

    f"dddd [<span style='color:{DATE_COLOR};'>]MMMM D[</span>]"

as the format.  Right now it changes the 's' in "span" to a 0.

**Comment by systemcatch** [comment]
We're looking at adding support for escaping in formatting, see #35, PR's welcome!
