### ISSUE TITLE
How to parse date?

### ISSUE THREAD

**Issue by ZeusFSX** [crsmithdev/arrow#691]
Can anyone help, how to parse date like this ```2019-10-09T21:25+3:00```?

**Comment by jadchaar** [comment]
@ZeusFSX according to the [ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601), timezones should be zero padded. Parsing `2019-10-09T21:25+03:00` should work seamlessly as follows:

```shell
venv ❯ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.15.2'
>>> arrow.get("2019-10-09T21:25+03:00")
<Arrow [2019-10-09T21:25:00+03:00]>
```

Arrow does not parse single digit hours not only because of the ISO 8601 time standard, but also because it would be a bit inconsistent to allow for single hours but not single digit minutes.

Does this help?

**Comment by ZeusFSX** [comment]
I know about ISO 8601, but when I parse some website, I got timezone without zero-padded, maybe you know how to replace +3:00 -> +03:00?

**Comment by jadchaar** [comment]
Hey @ZeusFSX, thanks for the follow up. I am discussing with @systemcatch whether or not we should allow +3:00 by default in Arrow. I will keep you posted.

As for a work around in the meantime, you can use a regex as follows:

```shell
venv ❯ python3                                                               
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> plus_tz = "2019-10-09T21:25+3:00"
>>> minus_tz = "2019-10-09T21:25-3:00"
>>> match_pattern = r"([\+\-])(\d{1}\:\d{2})"
>>> re.sub(match_pattern, r"\g<1>0\g<2>", plus_tz)
'2019-10-09T21:25+03:00'
>>> re.sub(match_pattern, r"\g<1>0\g<2>", minus_tz)
'2019-10-09T21:25-03:00'
```
This will match on the timezone portion of the string and substitute a 0 between the sign and the original timezone string.

I hope this helps :).

**Comment by jadchaar** [comment]
Hey @ZeusFSX, feel free to re-open this issue, but for now I am going to close it as resolved :). Thanks!

**Comment by ZeusFSX** [comment]
Thanks @jadchaar, it's helpful :))
