### ISSUE TITLE
Comparing arrow dates

### ISSUE THREAD

**Issue by fabads** [crsmithdev/arrow#704]
Hello, 
This is not an issue, simply a question to clarify my understanding of the documentation.
I need to check if two dates are in the same year and month. Using arrow, what is the best practice to perfom this test? Use .month and .year or apply a .format('YYYY-MM') to the 2 arrow dates to compare?

Thanks for your help.

Fabrice

**Comment by systemcatch** [comment]
@fabads there isn't a preference either way, use whatever code style you prefer.

**Comment by jadchaar** [comment]
@fabads to add on the what Chris said, you can also use the built-in comparison operations of an arrow object (like subtracting and such to get a timedelta) and the `is_between` member function. There isn't really a best way to do it :).
