### ISSUE TITLE
Not well supported for Chinese

### ISSUE THREAD

**Issue by bobowang2017** [crsmithdev/arrow#715]
arrow.get('2019-10-20', tzinfo='local').humanize(locale='zh')

error:

ValueError: Humanization of the 'weeks' granularity is not currently translated in the 'zh' locale. Please consider making a contribution to this locale.

**Comment by jadchaar** [comment]
Hey @bobowang2017, this should have been fixed in version 0.15.4. Can you try upgrading arrow (`pip install -U arrow`) and tell us if that fixes the issue?

Thanks.

**Comment by bobowang2017** [comment]
@jadchaar The arrow version I used is 0.15.4. But I Found another way to solve it .

change the locale from 'zh' to 'zh_cn':

arrow.get(str(_time.get('last_run_time')), tzinfo=tzlocal()).humanize(locale='zh_cn')

this is ok.

Tkanks

**Comment by jadchaar** [comment]
@bobowang2017 I just tried this and it worked:

```shell
venv ❯ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.15.4'
>>> arrow.get("2019-10-20").humanize(granularity="week")
'2 weeks ago'
>>> arrow.get("2019-10-20").humanize(locale="zh", granularity="week")
'2周前'
```
