### ISSUE TITLE
Humanize: combine granularities

### ISSUE THREAD

**Issue by fabads** [crsmithdev/arrow#716]
Hello,

is it possible to get a combined results of different granularities, eg. 7 years and 10 months ?

BR.
Fabrice

**Comment by systemcatch** [comment]
Hi @fabads at the moment `humanize()` does not support having multiple levels of granularity.

**Comment by jadchaar** [comment]
That being said though, it would be a great feature to add! Feel free to contribute @fabads, this would be a great addition to the library.
