### ISSUE TITLE
String escape doesn't work

### ISSUE THREAD

**Issue by torioLuz** [crsmithdev/arrow#729]
## Issue Description

If I run `print(arrow.utcnow().format('YYYY-MM-DDTHH:mm:ss[h]'))`, I expect `2019-12-10T00:56:51h` to be returned, but I'm getting `2019-12-10T00:56:51[12]`

## System Info

- 🖥 **macOS 10.13.6**
- 🐍 **Python 3.7.4**
- 🏹 **0.14.4**

**Comment by jadchaar** [comment]
Hi @torioLuz, support for this feature was added in Arrow v0.15.3:

```shell
env ❯ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.15.4'
>>> arrow.utcnow().format('YYYY-MM-DDTHH:mm:ss[h]')
2019-12-10T01:25:56h
```

Please upgrade Arrow to access these features :).
