### ISSUE TITLE
Replace class setup functions with Pytest fixtures

### ISSUE THREAD

**Issue by jadchaar** [crsmithdev/arrow#760]
Since we recently refactored the tests to use Pytest, it would be nice to convert the existing unittest-style setup/teardown class functions into Pytest-style fixtures. This would lead to better maintainability and compatibility going forward.

An example of the `setup_class(cls)` code that should be replaced: https://github.com/crsmithdev/arrow/blob/master/tests/test_factory.py#L17

**Comment by krisfremen** [comment]
I'm gonna tackle this issue this weekend.

**Comment by jadchaar** [comment]
Great to have you back @krisfremen!

**Comment by krisfremen** [comment]
@jadchaar good to be back, pull request ready for review :)
