### ISSUE TITLE
Add common format strings

### ISSUE THREAD

**Issue by jadchaar** [crsmithdev/arrow#762]
## Feature Request

Pendulum has a nice feature that allows you to make a function call on a Pendulum object to automatically get a pre-formatted, common string (e.g. a cookie time string). See this page for examples: https://pendulum.eustace.io/docs/#common-formats.

**Comment by rbandrews3** [comment]
Hi, I am interested in working on this issue. I forked the repository, cloned that repo, and ran "pip install -U arrow". It seems to successfully install, but when I try to run some of the test files, I get various errors with import packages. I am wondering if this is normal, or if we have done something wrong in setup. 

_Examples of some issues:_
"Traceback (most recent call last):
  File "tests/test_parser.py", line 17, in <module>
    from .utils import make_full_tz_list
ImportError: attempted relative import with no known parent package"

"Traceback (most recent call last):
  File "test_factory.py", line 12, in <module>
    from .utils import assert_datetime_equality
ModuleNotFoundError: No module named '__main__.utils'; '__main__' is not a package"

My friend, @ikoningstein, is working on this with me. Thank you in advance!

**Comment by jadchaar** [comment]
Hey @rbandrews3, by doing `pip install -U Arrow`, you are installing the packaged version from PyPi. Since you are developing the package, you need to simply execute the pytest test cases like this:

```shell
make build37 # replace with whatever python version you have on your system
pytest -v tests # this assumes you are in the root arrow directory
```

Or, you can use Tox (recommended) since this handles creating the virtual environment and installing the dependencies for you:
```shell
pip install -U tox
tox
```
The `tox` step runs linting and runs the tests on available python versions that are installed on your system.

**Comment by ikoningstein** [comment]
Thanks so much! We got the library running smoothly now. @rbandrews3  and I read through the documentation on the Pendulum common formatting, and want to confirm that this feature requires the implementation of the following functions. 

- dt.to_atom_string()
- dt.to_cookie_string()
- dt.to_iso8601_string()
- dt.to_rfc822_string()
- dt.to_rfc850_string()
- dt.to_rfc1036_string()
- dt.to_rfc1123_string()
- dt.to_rfc2822_string()
- dt.to_rfc3339_string()
- dt.to_rss_string()
- dt.to_w3c_string()

Thanks!

**Comment by jadchaar** [comment]
You do not have to implement all of them if you do not want to, so you can make a call on which of the functions you would like to implement based on the workload. These functions will most likely live in the Arrow formatter`format.py`.

**Comment by systemcatch** [comment]
Maybe just start with the most common RFC's and the cookie one.

**Comment by amylavar1** [comment]
Hi! I'm working on a different issue but had the same question as @rbandrews3 above! I cloned the repo and am trying to figure out how to build it but I am struggling a little - running the make command is not working and I'm not sure if I'm missing any build steps or installations. Do you have steps to share on how to properly build and run the code?

**Comment by rbandrews3** [comment]
@amylavar1 after installing arrow, we ran the tox commands that jad posted instead of the make commands and this worked for us! It’s the second comment on this post.

**Comment by jadchaar** [comment]
> Hi! I'm working on a different issue but had the same question as @rbandrews3 above! I cloned the repo and am trying to figure out how to build it but I am struggling a little - running the make command is not working and I'm not sure if I'm missing any build steps or installations. Do you have steps to share on how to properly build and run the code?

@amylavar1 No problem. I should definitely create some getting started documentation in the future, but here is what I recommend:

Rather than cloning the repo, you need to fork it and clone your fork. Once you fork it, you can create a branch on your forked copy of the repo and that is what you can PR into this official repository.

Also, like Rebecca stated, we recommend using Tox as it is cross platform and works across Windows, Mac, and Linux. You simply need to run `tox` to run all the tests and linting operations on all python versions that are available on your machine. If you know you have a particular python version (e.g. 3.8), you can run `tox -e py38`.

**Comment by amylavar1** [comment]
@jadchaar Hi! So I tried to follow and run the tox commands but I am getting an invocation error when I run tox -e py27.

**Comment by jadchaar** [comment]
> @jadchaar Hi! So I tried to follow and run the tox commands but I am getting an invocation error when I run tox -e py27.

Do you get this error when you just run `tox` without the environment argument?

**Comment by amylavar1** [comment]
Yes I get the same errors running tox alone

**Comment by jadchaar** [comment]
@amylavar1 do you think you can make a new issue thread [here](https://github.com/crsmithdev/arrow/issues) and we can continue this debugging conversation there? In your post, please include a screenshot or a copy of the terminal output you are receiving.

**Comment by amylavar1** [comment]
Yup, it's here: https://github.com/crsmithdev/arrow/issues/771

**Comment by systemcatch** [comment]
Done in #791
