### ISSUE TITLE
Problem with building - running Tox commands

### ISSUE THREAD

**Issue by amylavar1** [crsmithdev/arrow#771]
I followed the commands I saw in comment thread - installing Tox and then running the tox -e 37 command (the tox command alone gave a lot of environment errors) and there were a ton of issues, but here is the summary:

![Screen Shot 2020-04-09 at 6 57 32 PM](https://user-images.githubusercontent.com/23154272/78947660-ff495a80-7a93-11ea-94d4-b965c911910f.png)

**Comment by jadchaar** [comment]
Hmm this seems like an issue with your Python/pip installation. Can you try running `make build37` instead rather than using tox? Once you run that, you should be able to run the tests with `make test`.

**Comment by amylavar1** [comment]
it worked, thank you so much!
