### ISSUE TITLE
Parsing ms and us int/float timestamps in arrow.get

### ISSUE THREAD

**Issue by manos** [crsmithdev/arrow#795]
## Issue Description

Reading the docs, I should be able to supply a timestamp in milliseconds or microseconds, formatted as an int or float. When I pass a millisecond timestamp, I get ValueError - it only seems to work with seconds.

Expected:
```
>>> arrow.get(1590889920000.0).timestamp
1590889920000
```

Actual:
```
>>> arrow.get(1590889920000.0).timestamp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/charlie/Library/Python/3.7/lib/python/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/Users/charlie/Library/Python/3.7/lib/python/site-packages/arrow/factory.py", line 176, in get
    return self.type.fromtimestamp(arg, tzinfo=tz)
  File "/Users/charlie/Library/Python/3.7/lib/python/site-packages/arrow/arrow.py", line 161, in fromtimestamp
    dt = datetime.fromtimestamp(float(timestamp), tzinfo)
ValueError: year 52383 is out of range
```

## System Info

- 🖥 **OS name and version**: OS X 10.15.4
- 🐍 **Python version**: 3.7.6
- 🏹 **Arrow version**: 0.15.6

**Comment by systemcatch** [comment]
> Reading the docs, I should be able to supply a timestamp in milliseconds or microseconds, formatted as an int or float.

Hi @manos I don't think that is possible right now, timestamps (int or float) only work in seconds. However parsing a mili/microsecond timestamp string will work.

```shell
>>> ts=arrow.get("1590889920000", "x")
>>> ts
<Arrow [2020-05-31T01:52:00+00:00]>
>>> ts.format("x")
'1590889920000000'
```

Currently the formatting part will always show microseconds.

**Comment by jadchaar** [comment]
This seems to be related to our expanded timestamp logic only being limited to the control flow for parsing strings @systemcatch: https://github.com/crsmithdev/arrow/blob/e7a567628092f16189b0f9f5247d67fbff899ce5/arrow/parser.py#L414-L430.

We should decouple this functionality into a separate static method in `arrow.py` and make a call to it in all timestamp parsing cases (int, float, formatting string).
