### ISSUE TITLE
AttributeError: module 'arrow' has no attribute 'FORMAT_RFC3339'

### ISSUE THREAD

**Issue by MaximBazarov** [crsmithdev/arrow#809]
## Issue Description
Hi there, I'm trying to use the code from the documentation, but get this weird error

> AttributeError: module 'arrow' has no attribute 'FORMAT_RFC3339'

```python
import arrow
utc = arrow.utcnow()
print(utc.format(arrow.FORMAT_RFC3339))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'arrow' has no attribute 'FORMAT_RFC3339'
```

## System Info

- 🖥  macOS 10.15.1
- 🐍 Python 3.7.7
- 🏹 0.15.6

**Comment by jadchaar** [comment]
Hi @MaximBazarov, apologies for this. This is a feature in the upcoming 0.15.7 release: https://github.com/crsmithdev/arrow/pull/810, which should hopefully be released today if all goes well. Stay tuned. We need to work on making our docs update based on package versions :).
