### ISSUE TITLE
Fractional seconds not presented correctly

### ISSUE THREAD

**Issue by ivandigiusto** [crsmithdev/arrow#83]
It appears that fractional seconds are being treated as milliseconds, which is not what they are.

There also seems to be a difference in how fractional seconds are shown in Arrow class representation (incorrect) and with using a format string.

The Arrow class representation treats fractional seconds as 'number of microseconds.'

Problems with representation:

200 milliseconds represented as 2 microseconds
>>> arrow.get('2013-05-05T12:30:45.2+0030')
<Arrow [2013-05-05T12:30:45.000002+00:30]>

2 milliseconds represented as 2 microseconds
>>> arrow.get('2013-05-05T12:30:45.002+0030')
<Arrow [2013-05-05T12:30:45.000002+00:30]>

Problems with format:
Each of the examples of displaying 2 milliseconds is incorrect.

>>> arrow.get('2013-05-05T12:30:45.002+0030').format('YYYY-MM-DD HH:mm:ss.SSS ZZ')
'2013-05-05 12:30:45.0 +00:30'

>>> arrow.get('2013-05-05T12:30:45.002+0030').format('YYYY-MM-DD HH:mm:ss.SSSSS ZZ')
'2013-05-05 12:30:45.0 +00:30'

>>> arrow.get('2013-05-05T12:30:45.002+0030').format('YYYY-MM-DD HH:mm:ss.SSSSSS ZZ')
'2013-05-05 12:30:45.2 +00:30'

>>> arrow.get('2013-05-05T12:30:45.002+0030').format('YYYY-MM-DD HH:mm:ss.SSSSSSS ZZ')
'2013-05-05 12:30:45.20 +00:30'

**Comment by andrewelkins** [comment]
This was just fixed :)
