### ISSUE TITLE
Parse ISO 8601 basic format (hhmmss)

### ISSUE THREAD

**Issue by C4ptainCrunch** [crsmithdev/arrow#87]
At the moment being, `arrow.get` ignores the seconds if the datetime is in the basic format (`hhmmss`) and not in the extended format (`hh:mm:ss`) (see [wikipedia article](https://en.wikipedia.org/wiki/ISO_8601#Times) for more info)

```python
In [1]: arrow.get('19980119T070100')
Out[1]: <Arrow [1998-01-19T07:01:00+00:00]>

In [2]: arrow.get('19980119T070101') # added 1 sec but output is the same
Out[2]: <Arrow [1998-01-19T07:01:00+00:00]>
```

If I add microseconds, output is correct
```python
In [3]: arrow.get('19980119T070101.0')
Out[3]: <Arrow [1998-01-19T07:01:01+00:00]>
```

A part of the problem looks like the `has_seconds` detection in [arrow/parser.py:70](https://github.com/crsmithdev/arrow/blob/master/arrow/parser.py#L70) is wrong. (Sould check `len(time_parts[0])` if no `:` were found)

If it's ok with you i'll send a pull request in the next few days fixing the detection, the parsing (i didn't check i it need to be fixed as well) and adding new tests.

Edit : After a rapid test it looks like adding `has_seconds = not has_seconds and len(time_parts[0]) == 6` after line 70 fixes the problem. (But i still will investigate futher and write some tests)

**Comment by andrewelkins** [comment]
I can no longer reproduce this. Can you @C4ptainCrunch

**Comment by C4ptainCrunch** [comment]
I'm in a quite long trip abroad and I don't have access to a full blown
computer until mid September but I'll check as soon as I get back, I
promise :)

**Comment by C4ptainCrunch** [comment]
It looks that Arrow does not parse this format anymore

    >>> arrow.get('19980119T070101')
    ParserError: Could not match input to any of [u'YYYY-MM-DDTHH:mm'] on '19980119T070101'

**Comment by JoelChambers** [comment]
I can confirm that arrow 0.12.1 is still not parsing basic ISO-8601 date/time strings without separators, such as **20180710T230024** and **20180710T230024Z**. I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "arrow/api.py", line 22, in get
    return _factory.get(*args, **kwargs)
  File "arrow/factory.py", line 174, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "arrow/parser.py", line 119, in parse_iso
    return self._parse_multiformat(string, formats)
  File "arrow/parser.py", line 283, in _parse_multiformat
    raise ParserError('Could not match input to any of {0} on \'{1}\''.format(formats, string))
arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DDTHH:mm'] on '20180710T230024Z'
```

It looks like the `parse_iso` function needs to have more formats added to parse dates and datetimes without separators. I confess to not being good enough at Python myself to submit a code recommendation.
