### ISSUE TITLE
Accurate handling of parsing errors

### ISSUE THREAD

**Issue by vrutsky** [crsmithdev/arrow#91]
Arrow can silently fail to parse complete date string and return invalid result when date string partially matches one of formats.

Consider parsing SQLite date-time string:

```
>>> arrow.get('2014-01-25 01:22:58')
<Arrow [2014-01-25T00:00:00+00:00]>
```

Note that time part of date not parsed and were silently lost.

Or parsing even not date-time sting:

```
>>> arrow.get("Happy 2014!")
<Arrow [2014-01-01T00:00:00+00:00]>
```

**Comment by keynmol** [comment]
Hi, is there any movement on this? Or a workaround? We are parsing OG tags on pages and some of them have some really malformed shit there. And Arrow is not helping:

```
In [52]: arrow_get('blabla102015').isoformat()
Out[52]: '1020-01-01T00:00:00+00:00'
```

**Comment by jmagnusson** [comment]
Really annoying that it parses so relaxed. Almost worse than php date parsing.

**Comment by laruellef** [comment]
Ditto,
I would support bombing on incomplete parsing such as:
>>> arrow.get("02/01/2004")
<Arrow [2004-01-01T00:00:00+00:00]>

After months of use, I was unaware that this wasn't working until I tried it.
This has resulted in service affecting problems...

Would also be useful to document the complete list of supported formats,
is that avail anywhere?

**Comment by andrewelkins** [comment]
@laruellef I don't think it's documented anywhere.

@rutsky I agree, but inorder to not break backwards compatibility it would need to be a flag to be set.

**Comment by MarcoSulla** [comment]
I don't think JS and JS libraries are good example of robust design in general. moment.js it's a good library, but Python good practises enforces the use of exceptions (or at least to return a None, if you want a C-style speedup in your code)

**Comment by andrewelkins** [comment]
@MarcoSulla Agreed, it's just a basis, but doesn't mean Arrow has to implement it verbatim.

**Comment by systemcatch** [comment]
The current situation for all these examples.
```shell
>>> arrow.get('2014-01-25 01:22:58')
<Arrow [2014-01-25T01:22:58+00:00]>
>>> arrow.get('blabla102015').isoformat()
'1020-01-01T00:00:00+00:00'
>>> arrow.get("Happy 2014!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/arrow/arrow/api.py", line 22, in get
    return _factory.get(*args, **kwargs)
  File "/home/chris/arrow/arrow/factory.py", line 174, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "/home/chris/arrow/arrow/parser.py", line 119, in parse_iso
    return self._parse_multiformat(string, formats)
  File "/home/chris/arrow/arrow/parser.py", line 286, in _parse_multiformat
    raise ParserError('Could not match input to any of {} on \'{}\''.format(formats, string))
arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DD HH:mm'] on 'Happy 2014!'
>>> arrow.get("02/01/2004")
<Arrow [2004-01-01T00:00:00+00:00]>
>>> arrow.get("10/10/2016")
<Arrow [2016-01-01T00:00:00+00:00]>
>>> arrow.get("2016-1-10")
<Arrow [2016-01-01T00:00:00+00:00]>
```
