### ISSUE TITLE
Unformatted PyPI page

### ISSUE THREAD

**Issue by mgedmin** [crsmithdev/arrow#95]
https://pypi.python.org/pypi/arrow looks pretty bad:
![ekrano nuotrauka i 2014-02-13 09 10 25](https://f.cloud.github.com/assets/159967/2157533/f69aeb04-947d-11e3-812b-7537b7572d89.png)

This is because PyPI doesn't support Markdown.  It only supports ReStructuredText.

You can use pandoc to convert from md to rst, then replace the long description field on PyPI.

**Comment by mgedmin** [comment]
:sparkles: Thank you! :sparkles:

**Comment by andrewelkins** [comment]
Welcome
