### ISSUE TITLE
Coarse-grained humanize()

### ISSUE THREAD

**Issue by mgedmin** [crsmithdev/arrow#96]
I've a cron script that updates an HTML page once a day.  I'd like to avoid timestamps like "5 minutes ago" on that page.  Coarser approximations like "Today" or "5 days ago" would work fine for this use case.

I suggest a new `granularity` argument for the `humanize()` method, e.g.:

``` python
>>> t = arrow.utcnown().replace(minutes=-5)
>>> t.humanize(granularity='now') # default if you omit granularity
'5 minutes ago'
>>> t.humanize(granularity='minutes')
'5 minutes ago'
>>> t.humanize(granularity='hours')
'this hour'
>>> t.humanize(granularity='days')
'today'
>>> t.humanize(granularity='months')
'this month'
>>> t.humanize(granularity='years')
'this year'
```

If the difference between the reference point and the timestamp is less than the specified granularity, it would return a fixed string, otherwise it would do what it already does today.

Special-casing 'yesterday' and 'tomorrow' instead of ('1 day ago' and 'in 1 day') would be nice as well.  Maybe 'last/next month/year' too.

**Comment by andrewelkins** [comment]
This is handled by a PR
