### ISSUE TITLE
arrow.get() with two strings should support an optional tzinfo

### ISSUE THREAD

**Issue by pombredanne** [crsmithdev/arrow#98]
It would be great when you have a time stamp if could specify which tz it is in, even if the ts itself does not contain the information, such as local vs always forcing utc:
For instance something like this:

```
arrow.get('2014/02/05 09:23:44', 'YYYY/MM/DD HH:mm:ss', tzinfo=tz.tzlocal())
```

where the get factory would support something like:

```
        **Three** arguments, both ``str``, to parse the first according to the format of the second and the third is an optional tzinfo, defaulting to UTC::
```

**Comment by soxofaan** [comment]
:+1: 
I agree. I had the same problem and it took me more time than I anticipated to find another "trick" to workaround this:
```
arrow.get(arrow.get('2014/02/05 09:23:44', 'YYYY/MM/DD HH:mm:ss').datetime, 'local')
```

which is uglier than the solution of @pombredanne , so I'll happily change it to his one

**Comment by andrewelkins** [comment]
Will add this to the Wiki
